// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_core.sql

package store

import (
	"context"
	"database/sql"
)

const createActivityEvent = `-- name: CreateActivityEvent :exec
INSERT INTO activity_events (
  id, project_id, session_id, event_type, summary, metadata_json, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateActivityEventParams struct {
	ID           string         `json:"id"`
	ProjectID    string         `json:"project_id"`
	SessionID    sql.NullString `json:"session_id"`
	EventType    string         `json:"event_type"`
	Summary      string         `json:"summary"`
	MetadataJson string         `json:"metadata_json"`
	CreatedAt    string         `json:"created_at"`
}

func (q *Queries) CreateActivityEvent(ctx context.Context, arg CreateActivityEventParams) error {
	_, err := q.db.ExecContext(ctx, createActivityEvent,
		arg.ID,
		arg.ProjectID,
		arg.SessionID,
		arg.EventType,
		arg.Summary,
		arg.MetadataJson,
		arg.CreatedAt,
	)
	return err
}

const createAgentMessage = `-- name: CreateAgentMessage :exec
INSERT INTO agent_messages (
  id, session_id, role, body_markdown, metadata_json, created_at
) VALUES (?, ?, ?, ?, ?, ?)
`

type CreateAgentMessageParams struct {
	ID           string `json:"id"`
	SessionID    string `json:"session_id"`
	Role         string `json:"role"`
	BodyMarkdown string `json:"body_markdown"`
	MetadataJson string `json:"metadata_json"`
	CreatedAt    string `json:"created_at"`
}

func (q *Queries) CreateAgentMessage(ctx context.Context, arg CreateAgentMessageParams) error {
	_, err := q.db.ExecContext(ctx, createAgentMessage,
		arg.ID,
		arg.SessionID,
		arg.Role,
		arg.BodyMarkdown,
		arg.MetadataJson,
		arg.CreatedAt,
	)
	return err
}

const createAgentMessageForProject = `-- name: CreateAgentMessageForProject :exec
INSERT INTO agent_messages (
  id, session_id, role, body_markdown, metadata_json, created_at
)
SELECT
  ?1,
  agent_sessions.id,
  ?2,
  ?3,
  ?4,
  ?5
FROM agent_sessions
WHERE agent_sessions.id = ?6
  AND agent_sessions.project_id = ?7
`

type CreateAgentMessageForProjectParams struct {
	ID           string `json:"id"`
	Role         string `json:"role"`
	BodyMarkdown string `json:"body_markdown"`
	MetadataJson string `json:"metadata_json"`
	CreatedAt    string `json:"created_at"`
	SessionID    string `json:"session_id"`
	ProjectID    string `json:"project_id"`
}

func (q *Queries) CreateAgentMessageForProject(ctx context.Context, arg CreateAgentMessageForProjectParams) error {
	_, err := q.db.ExecContext(ctx, createAgentMessageForProject,
		arg.ID,
		arg.Role,
		arg.BodyMarkdown,
		arg.MetadataJson,
		arg.CreatedAt,
		arg.SessionID,
		arg.ProjectID,
	)
	return err
}

const createAgentSession = `-- name: CreateAgentSession :exec
INSERT INTO agent_sessions (
  id, project_id, title, action_kind, model_variant_id, apply_mode, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAgentSessionParams struct {
	ID             string         `json:"id"`
	ProjectID      string         `json:"project_id"`
	Title          string         `json:"title"`
	ActionKind     string         `json:"action_kind"`
	ModelVariantID sql.NullString `json:"model_variant_id"`
	ApplyMode      string         `json:"apply_mode"`
	CreatedAt      string         `json:"created_at"`
	UpdatedAt      string         `json:"updated_at"`
}

func (q *Queries) CreateAgentSession(ctx context.Context, arg CreateAgentSessionParams) error {
	_, err := q.db.ExecContext(ctx, createAgentSession,
		arg.ID,
		arg.ProjectID,
		arg.Title,
		arg.ActionKind,
		arg.ModelVariantID,
		arg.ApplyMode,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createGenerationCandidate = `-- name: CreateGenerationCandidate :exec
INSERT INTO generation_candidates (
  id, project_id, session_id, content_item_id, action_kind, operation_kind,
  expected_revision, selection_start, selection_end, insert_position,
  original_markdown, generated_markdown, reason, model_variant_id, status,
  created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateGenerationCandidateParams struct {
	ID                string         `json:"id"`
	ProjectID         string         `json:"project_id"`
	SessionID         string         `json:"session_id"`
	ContentItemID     string         `json:"content_item_id"`
	ActionKind        string         `json:"action_kind"`
	OperationKind     string         `json:"operation_kind"`
	ExpectedRevision  int64          `json:"expected_revision"`
	SelectionStart    sql.NullInt64  `json:"selection_start"`
	SelectionEnd      sql.NullInt64  `json:"selection_end"`
	InsertPosition    sql.NullInt64  `json:"insert_position"`
	OriginalMarkdown  string         `json:"original_markdown"`
	GeneratedMarkdown string         `json:"generated_markdown"`
	Reason            string         `json:"reason"`
	ModelVariantID    sql.NullString `json:"model_variant_id"`
	Status            string         `json:"status"`
	CreatedAt         string         `json:"created_at"`
	UpdatedAt         string         `json:"updated_at"`
}

func (q *Queries) CreateGenerationCandidate(ctx context.Context, arg CreateGenerationCandidateParams) error {
	_, err := q.db.ExecContext(ctx, createGenerationCandidate,
		arg.ID,
		arg.ProjectID,
		arg.SessionID,
		arg.ContentItemID,
		arg.ActionKind,
		arg.OperationKind,
		arg.ExpectedRevision,
		arg.SelectionStart,
		arg.SelectionEnd,
		arg.InsertPosition,
		arg.OriginalMarkdown,
		arg.GeneratedMarkdown,
		arg.Reason,
		arg.ModelVariantID,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createModelVariant = `-- name: CreateModelVariant :exec
INSERT INTO model_variants (
  id, provider_config_id, name, model, temperature, max_output_tokens,
  context_window_tokens, input_price_per_million, output_price_per_million,
  cache_read_price_per_million, cache_write_price_per_million,
  request_token_field, reasoning_format, compatibility_json, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateModelVariantParams struct {
	ID                        string  `json:"id"`
	ProviderConfigID          string  `json:"provider_config_id"`
	Name                      string  `json:"name"`
	Model                     string  `json:"model"`
	Temperature               float64 `json:"temperature"`
	MaxOutputTokens           int64   `json:"max_output_tokens"`
	ContextWindowTokens       int64   `json:"context_window_tokens"`
	InputPricePerMillion      float64 `json:"input_price_per_million"`
	OutputPricePerMillion     float64 `json:"output_price_per_million"`
	CacheReadPricePerMillion  float64 `json:"cache_read_price_per_million"`
	CacheWritePricePerMillion float64 `json:"cache_write_price_per_million"`
	RequestTokenField         string  `json:"request_token_field"`
	ReasoningFormat           string  `json:"reasoning_format"`
	CompatibilityJson         string  `json:"compatibility_json"`
	CreatedAt                 string  `json:"created_at"`
	UpdatedAt                 string  `json:"updated_at"`
}

func (q *Queries) CreateModelVariant(ctx context.Context, arg CreateModelVariantParams) error {
	_, err := q.db.ExecContext(ctx, createModelVariant,
		arg.ID,
		arg.ProviderConfigID,
		arg.Name,
		arg.Model,
		arg.Temperature,
		arg.MaxOutputTokens,
		arg.ContextWindowTokens,
		arg.InputPricePerMillion,
		arg.OutputPricePerMillion,
		arg.CacheReadPricePerMillion,
		arg.CacheWritePricePerMillion,
		arg.RequestTokenField,
		arg.ReasoningFormat,
		arg.CompatibilityJson,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createPromptContextSnapshot = `-- name: CreatePromptContextSnapshot :exec
INSERT INTO prompt_context_snapshots (
  id, prompt_record_id, source_key, source_version, rendered_markdown, value_json, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreatePromptContextSnapshotParams struct {
	ID               string `json:"id"`
	PromptRecordID   string `json:"prompt_record_id"`
	SourceKey        string `json:"source_key"`
	SourceVersion    string `json:"source_version"`
	RenderedMarkdown string `json:"rendered_markdown"`
	ValueJson        string `json:"value_json"`
	CreatedAt        string `json:"created_at"`
}

func (q *Queries) CreatePromptContextSnapshot(ctx context.Context, arg CreatePromptContextSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, createPromptContextSnapshot,
		arg.ID,
		arg.PromptRecordID,
		arg.SourceKey,
		arg.SourceVersion,
		arg.RenderedMarkdown,
		arg.ValueJson,
		arg.CreatedAt,
	)
	return err
}

const createPromptRecord = `-- name: CreatePromptRecord :exec
INSERT INTO prompt_records (
  id, project_id, session_id, provider_name, model_name, action_kind,
  request_json, response_json, input_tokens, output_tokens, cache_read_tokens,
  cache_write_tokens, total_tokens, input_cost, output_cost, cache_read_cost,
  cache_write_cost, total_cost, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreatePromptRecordParams struct {
	ID               string         `json:"id"`
	ProjectID        string         `json:"project_id"`
	SessionID        sql.NullString `json:"session_id"`
	ProviderName     string         `json:"provider_name"`
	ModelName        string         `json:"model_name"`
	ActionKind       string         `json:"action_kind"`
	RequestJson      string         `json:"request_json"`
	ResponseJson     string         `json:"response_json"`
	InputTokens      int64          `json:"input_tokens"`
	OutputTokens     int64          `json:"output_tokens"`
	CacheReadTokens  int64          `json:"cache_read_tokens"`
	CacheWriteTokens int64          `json:"cache_write_tokens"`
	TotalTokens      int64          `json:"total_tokens"`
	InputCost        float64        `json:"input_cost"`
	OutputCost       float64        `json:"output_cost"`
	CacheReadCost    float64        `json:"cache_read_cost"`
	CacheWriteCost   float64        `json:"cache_write_cost"`
	TotalCost        float64        `json:"total_cost"`
	CreatedAt        string         `json:"created_at"`
}

func (q *Queries) CreatePromptRecord(ctx context.Context, arg CreatePromptRecordParams) error {
	_, err := q.db.ExecContext(ctx, createPromptRecord,
		arg.ID,
		arg.ProjectID,
		arg.SessionID,
		arg.ProviderName,
		arg.ModelName,
		arg.ActionKind,
		arg.RequestJson,
		arg.ResponseJson,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CacheReadTokens,
		arg.CacheWriteTokens,
		arg.TotalTokens,
		arg.InputCost,
		arg.OutputCost,
		arg.CacheReadCost,
		arg.CacheWriteCost,
		arg.TotalCost,
		arg.CreatedAt,
	)
	return err
}

const createProviderConfig = `-- name: CreateProviderConfig :exec
INSERT INTO provider_configs (
  id, author_id, name, base_url, api_key_encrypted, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateProviderConfigParams struct {
	ID              string `json:"id"`
	AuthorID        string `json:"author_id"`
	Name            string `json:"name"`
	BaseUrl         string `json:"base_url"`
	ApiKeyEncrypted string `json:"api_key_encrypted"`
	CreatedAt       string `json:"created_at"`
	UpdatedAt       string `json:"updated_at"`
}

func (q *Queries) CreateProviderConfig(ctx context.Context, arg CreateProviderConfigParams) error {
	_, err := q.db.ExecContext(ctx, createProviderConfig,
		arg.ID,
		arg.AuthorID,
		arg.Name,
		arg.BaseUrl,
		arg.ApiKeyEncrypted,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createToolResultArtifact = `-- name: CreateToolResultArtifact :exec
INSERT INTO tool_result_artifacts (
  id, project_id, session_id, tool_call_id, tool_name, full_result_json,
  model_visible_markdown, truncated, full_result_bytes, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateToolResultArtifactParams struct {
	ID                   string         `json:"id"`
	ProjectID            string         `json:"project_id"`
	SessionID            sql.NullString `json:"session_id"`
	ToolCallID           string         `json:"tool_call_id"`
	ToolName             string         `json:"tool_name"`
	FullResultJson       string         `json:"full_result_json"`
	ModelVisibleMarkdown string         `json:"model_visible_markdown"`
	Truncated            int64          `json:"truncated"`
	FullResultBytes      int64          `json:"full_result_bytes"`
	CreatedAt            string         `json:"created_at"`
}

func (q *Queries) CreateToolResultArtifact(ctx context.Context, arg CreateToolResultArtifactParams) error {
	_, err := q.db.ExecContext(ctx, createToolResultArtifact,
		arg.ID,
		arg.ProjectID,
		arg.SessionID,
		arg.ToolCallID,
		arg.ToolName,
		arg.FullResultJson,
		arg.ModelVisibleMarkdown,
		arg.Truncated,
		arg.FullResultBytes,
		arg.CreatedAt,
	)
	return err
}

const deleteExpiredPromptRecords = `-- name: DeleteExpiredPromptRecords :exec
DELETE FROM prompt_records
WHERE project_id = ?1
  AND created_at < ?2
`

type DeleteExpiredPromptRecordsParams struct {
	ProjectID string `json:"project_id"`
	Cutoff    string `json:"cutoff"`
}

func (q *Queries) DeleteExpiredPromptRecords(ctx context.Context, arg DeleteExpiredPromptRecordsParams) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredPromptRecords, arg.ProjectID, arg.Cutoff)
	return err
}

const deleteModelVariant = `-- name: DeleteModelVariant :exec
DELETE FROM model_variants
WHERE model_variants.id = ?1
  AND provider_config_id IN (
    SELECT provider_configs.id FROM provider_configs
    WHERE provider_configs.author_id = ?2
  )
`

type DeleteModelVariantParams struct {
	ID       string `json:"id"`
	AuthorID string `json:"author_id"`
}

func (q *Queries) DeleteModelVariant(ctx context.Context, arg DeleteModelVariantParams) error {
	_, err := q.db.ExecContext(ctx, deleteModelVariant, arg.ID, arg.AuthorID)
	return err
}

const deleteProviderConfig = `-- name: DeleteProviderConfig :exec
DELETE FROM provider_configs
WHERE id = ?1
  AND author_id = ?2
`

type DeleteProviderConfigParams struct {
	ID       string `json:"id"`
	AuthorID string `json:"author_id"`
}

func (q *Queries) DeleteProviderConfig(ctx context.Context, arg DeleteProviderConfigParams) error {
	_, err := q.db.ExecContext(ctx, deleteProviderConfig, arg.ID, arg.AuthorID)
	return err
}

const getAgentSession = `-- name: GetAgentSession :one
SELECT id, project_id, title, action_kind, model_variant_id, apply_mode, created_at, updated_at FROM agent_sessions
WHERE project_id = ? AND id = ?
`

type GetAgentSessionParams struct {
	ProjectID string `json:"project_id"`
	ID        string `json:"id"`
}

func (q *Queries) GetAgentSession(ctx context.Context, arg GetAgentSessionParams) (AgentSession, error) {
	row := q.db.QueryRowContext(ctx, getAgentSession, arg.ProjectID, arg.ID)
	var i AgentSession
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.ActionKind,
		&i.ModelVariantID,
		&i.ApplyMode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGenerationCandidate = `-- name: GetGenerationCandidate :one
SELECT id, project_id, session_id, content_item_id, action_kind, operation_kind, expected_revision, selection_start, selection_end, insert_position, original_markdown, generated_markdown, reason, model_variant_id, status, created_at, updated_at FROM generation_candidates
WHERE project_id = ? AND id = ?
`

type GetGenerationCandidateParams struct {
	ProjectID string `json:"project_id"`
	ID        string `json:"id"`
}

func (q *Queries) GetGenerationCandidate(ctx context.Context, arg GetGenerationCandidateParams) (GenerationCandidate, error) {
	row := q.db.QueryRowContext(ctx, getGenerationCandidate, arg.ProjectID, arg.ID)
	var i GenerationCandidate
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SessionID,
		&i.ContentItemID,
		&i.ActionKind,
		&i.OperationKind,
		&i.ExpectedRevision,
		&i.SelectionStart,
		&i.SelectionEnd,
		&i.InsertPosition,
		&i.OriginalMarkdown,
		&i.GeneratedMarkdown,
		&i.Reason,
		&i.ModelVariantID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getModelVariant = `-- name: GetModelVariant :one
SELECT model_variants.id, model_variants.provider_config_id, model_variants.name, model_variants.model, model_variants.temperature, model_variants.max_output_tokens, model_variants.context_window_tokens, model_variants.input_price_per_million, model_variants.output_price_per_million, model_variants.cache_read_price_per_million, model_variants.cache_write_price_per_million, model_variants.request_token_field, model_variants.reasoning_format, model_variants.compatibility_json, model_variants.created_at, model_variants.updated_at
FROM model_variants
JOIN provider_configs ON provider_configs.id = model_variants.provider_config_id
WHERE model_variants.id = ?1
  AND provider_configs.author_id = ?2
`

type GetModelVariantParams struct {
	ID       string `json:"id"`
	AuthorID string `json:"author_id"`
}

func (q *Queries) GetModelVariant(ctx context.Context, arg GetModelVariantParams) (ModelVariant, error) {
	row := q.db.QueryRowContext(ctx, getModelVariant, arg.ID, arg.AuthorID)
	var i ModelVariant
	err := row.Scan(
		&i.ID,
		&i.ProviderConfigID,
		&i.Name,
		&i.Model,
		&i.Temperature,
		&i.MaxOutputTokens,
		&i.ContextWindowTokens,
		&i.InputPricePerMillion,
		&i.OutputPricePerMillion,
		&i.CacheReadPricePerMillion,
		&i.CacheWritePricePerMillion,
		&i.RequestTokenField,
		&i.ReasoningFormat,
		&i.CompatibilityJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPromptProfile = `-- name: GetPromptProfile :one
SELECT id, project_id, genre, tense, pov, voice, instructions_markdown, prompt_record_retention_days, created_at, updated_at FROM prompt_profiles
WHERE project_id = ?
`

func (q *Queries) GetPromptProfile(ctx context.Context, projectID string) (PromptProfile, error) {
	row := q.db.QueryRowContext(ctx, getPromptProfile, projectID)
	var i PromptProfile
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Genre,
		&i.Tense,
		&i.Pov,
		&i.Voice,
		&i.InstructionsMarkdown,
		&i.PromptRecordRetentionDays,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProviderConfig = `-- name: GetProviderConfig :one
SELECT id, author_id, name, base_url, api_key_encrypted, created_at, updated_at FROM provider_configs
WHERE id = ?1
  AND author_id = ?2
`

type GetProviderConfigParams struct {
	ID       string `json:"id"`
	AuthorID string `json:"author_id"`
}

func (q *Queries) GetProviderConfig(ctx context.Context, arg GetProviderConfigParams) (ProviderConfig, error) {
	row := q.db.QueryRowContext(ctx, getProviderConfig, arg.ID, arg.AuthorID)
	var i ProviderConfig
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Name,
		&i.BaseUrl,
		&i.ApiKeyEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActivityEvents = `-- name: ListActivityEvents :many
SELECT id, project_id, session_id, event_type, summary, metadata_json, created_at FROM activity_events
WHERE project_id = ?
ORDER BY created_at DESC
LIMIT ?2
`

type ListActivityEventsParams struct {
	ProjectID string `json:"project_id"`
	Limit     int64  `json:"limit"`
}

func (q *Queries) ListActivityEvents(ctx context.Context, arg ListActivityEventsParams) ([]ActivityEvent, error) {
	rows, err := q.db.QueryContext(ctx, listActivityEvents, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActivityEvent
	for rows.Next() {
		var i ActivityEvent
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SessionID,
			&i.EventType,
			&i.Summary,
			&i.MetadataJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentMessages = `-- name: ListAgentMessages :many
SELECT id, session_id, role, body_markdown, metadata_json, created_at FROM agent_messages
WHERE session_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListAgentMessages(ctx context.Context, sessionID string) ([]AgentMessage, error) {
	rows, err := q.db.QueryContext(ctx, listAgentMessages, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentMessage
	for rows.Next() {
		var i AgentMessage
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.BodyMarkdown,
			&i.MetadataJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentMessagesForProject = `-- name: ListAgentMessagesForProject :many
SELECT agent_messages.id, agent_messages.session_id, agent_messages.role, agent_messages.body_markdown, agent_messages.metadata_json, agent_messages.created_at
FROM agent_messages
JOIN agent_sessions ON agent_sessions.id = agent_messages.session_id
WHERE agent_messages.session_id = ?1
  AND agent_sessions.project_id = ?2
ORDER BY agent_messages.created_at ASC
`

type ListAgentMessagesForProjectParams struct {
	SessionID string `json:"session_id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) ListAgentMessagesForProject(ctx context.Context, arg ListAgentMessagesForProjectParams) ([]AgentMessage, error) {
	rows, err := q.db.QueryContext(ctx, listAgentMessagesForProject, arg.SessionID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentMessage
	for rows.Next() {
		var i AgentMessage
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.BodyMarkdown,
			&i.MetadataJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentSessions = `-- name: ListAgentSessions :many
SELECT id, project_id, title, action_kind, model_variant_id, apply_mode, created_at, updated_at FROM agent_sessions
WHERE project_id = ?
ORDER BY updated_at DESC
LIMIT ?2
`

type ListAgentSessionsParams struct {
	ProjectID string `json:"project_id"`
	Limit     int64  `json:"limit"`
}

func (q *Queries) ListAgentSessions(ctx context.Context, arg ListAgentSessionsParams) ([]AgentSession, error) {
	rows, err := q.db.QueryContext(ctx, listAgentSessions, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentSession
	for rows.Next() {
		var i AgentSession
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.ActionKind,
			&i.ModelVariantID,
			&i.ApplyMode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGenerationCandidates = `-- name: ListGenerationCandidates :many
SELECT id, project_id, session_id, content_item_id, action_kind, operation_kind, expected_revision, selection_start, selection_end, insert_position, original_markdown, generated_markdown, reason, model_variant_id, status, created_at, updated_at FROM generation_candidates
WHERE project_id = ?1
  AND session_id = ?2
ORDER BY created_at DESC
`

type ListGenerationCandidatesParams struct {
	ProjectID string `json:"project_id"`
	SessionID string `json:"session_id"`
}

func (q *Queries) ListGenerationCandidates(ctx context.Context, arg ListGenerationCandidatesParams) ([]GenerationCandidate, error) {
	rows, err := q.db.QueryContext(ctx, listGenerationCandidates, arg.ProjectID, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GenerationCandidate
	for rows.Next() {
		var i GenerationCandidate
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SessionID,
			&i.ContentItemID,
			&i.ActionKind,
			&i.OperationKind,
			&i.ExpectedRevision,
			&i.SelectionStart,
			&i.SelectionEnd,
			&i.InsertPosition,
			&i.OriginalMarkdown,
			&i.GeneratedMarkdown,
			&i.Reason,
			&i.ModelVariantID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModelVariantsByAuthor = `-- name: ListModelVariantsByAuthor :many
SELECT model_variants.id, model_variants.provider_config_id, model_variants.name, model_variants.model, model_variants.temperature, model_variants.max_output_tokens, model_variants.context_window_tokens, model_variants.input_price_per_million, model_variants.output_price_per_million, model_variants.cache_read_price_per_million, model_variants.cache_write_price_per_million, model_variants.request_token_field, model_variants.reasoning_format, model_variants.compatibility_json, model_variants.created_at, model_variants.updated_at
FROM model_variants
JOIN provider_configs ON provider_configs.id = model_variants.provider_config_id
WHERE provider_configs.author_id = ?
ORDER BY provider_configs.name ASC, model_variants.name ASC
`

func (q *Queries) ListModelVariantsByAuthor(ctx context.Context, authorID string) ([]ModelVariant, error) {
	rows, err := q.db.QueryContext(ctx, listModelVariantsByAuthor, authorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModelVariant
	for rows.Next() {
		var i ModelVariant
		if err := rows.Scan(
			&i.ID,
			&i.ProviderConfigID,
			&i.Name,
			&i.Model,
			&i.Temperature,
			&i.MaxOutputTokens,
			&i.ContextWindowTokens,
			&i.InputPricePerMillion,
			&i.OutputPricePerMillion,
			&i.CacheReadPricePerMillion,
			&i.CacheWritePricePerMillion,
			&i.RequestTokenField,
			&i.ReasoningFormat,
			&i.CompatibilityJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModelVariantsByProvider = `-- name: ListModelVariantsByProvider :many
SELECT model_variants.id, model_variants.provider_config_id, model_variants.name, model_variants.model, model_variants.temperature, model_variants.max_output_tokens, model_variants.context_window_tokens, model_variants.input_price_per_million, model_variants.output_price_per_million, model_variants.cache_read_price_per_million, model_variants.cache_write_price_per_million, model_variants.request_token_field, model_variants.reasoning_format, model_variants.compatibility_json, model_variants.created_at, model_variants.updated_at
FROM model_variants
JOIN provider_configs ON provider_configs.id = model_variants.provider_config_id
WHERE model_variants.provider_config_id = ?1
  AND provider_configs.author_id = ?2
ORDER BY model_variants.name ASC
`

type ListModelVariantsByProviderParams struct {
	ProviderConfigID string `json:"provider_config_id"`
	AuthorID         string `json:"author_id"`
}

func (q *Queries) ListModelVariantsByProvider(ctx context.Context, arg ListModelVariantsByProviderParams) ([]ModelVariant, error) {
	rows, err := q.db.QueryContext(ctx, listModelVariantsByProvider, arg.ProviderConfigID, arg.AuthorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModelVariant
	for rows.Next() {
		var i ModelVariant
		if err := rows.Scan(
			&i.ID,
			&i.ProviderConfigID,
			&i.Name,
			&i.Model,
			&i.Temperature,
			&i.MaxOutputTokens,
			&i.ContextWindowTokens,
			&i.InputPricePerMillion,
			&i.OutputPricePerMillion,
			&i.CacheReadPricePerMillion,
			&i.CacheWritePricePerMillion,
			&i.RequestTokenField,
			&i.ReasoningFormat,
			&i.CompatibilityJson,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPromptContextSnapshots = `-- name: ListPromptContextSnapshots :many
SELECT id, prompt_record_id, source_key, source_version, rendered_markdown, value_json, created_at FROM prompt_context_snapshots
WHERE prompt_record_id = ?
ORDER BY source_key ASC
`

func (q *Queries) ListPromptContextSnapshots(ctx context.Context, promptRecordID string) ([]PromptContextSnapshot, error) {
	rows, err := q.db.QueryContext(ctx, listPromptContextSnapshots, promptRecordID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PromptContextSnapshot
	for rows.Next() {
		var i PromptContextSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.PromptRecordID,
			&i.SourceKey,
			&i.SourceVersion,
			&i.RenderedMarkdown,
			&i.ValueJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPromptRecords = `-- name: ListPromptRecords :many
SELECT id, project_id, session_id, provider_name, model_name, action_kind, request_json, response_json, input_tokens, output_tokens, cache_read_tokens, cache_write_tokens, total_tokens, input_cost, output_cost, cache_read_cost, cache_write_cost, total_cost, created_at FROM prompt_records
WHERE project_id = ?
ORDER BY created_at DESC
LIMIT ?2
`

type ListPromptRecordsParams struct {
	ProjectID string `json:"project_id"`
	Limit     int64  `json:"limit"`
}

func (q *Queries) ListPromptRecords(ctx context.Context, arg ListPromptRecordsParams) ([]PromptRecord, error) {
	rows, err := q.db.QueryContext(ctx, listPromptRecords, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PromptRecord
	for rows.Next() {
		var i PromptRecord
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SessionID,
			&i.ProviderName,
			&i.ModelName,
			&i.ActionKind,
			&i.RequestJson,
			&i.ResponseJson,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheReadTokens,
			&i.CacheWriteTokens,
			&i.TotalTokens,
			&i.InputCost,
			&i.OutputCost,
			&i.CacheReadCost,
			&i.CacheWriteCost,
			&i.TotalCost,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviderConfigs = `-- name: ListProviderConfigs :many
SELECT id, author_id, name, base_url, api_key_encrypted, created_at, updated_at FROM provider_configs
WHERE author_id = ?
ORDER BY name ASC
`

func (q *Queries) ListProviderConfigs(ctx context.Context, authorID string) ([]ProviderConfig, error) {
	rows, err := q.db.QueryContext(ctx, listProviderConfigs, authorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProviderConfig
	for rows.Next() {
		var i ProviderConfig
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Name,
			&i.BaseUrl,
			&i.ApiKeyEncrypted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listToolResultArtifacts = `-- name: ListToolResultArtifacts :many
SELECT id, project_id, session_id, tool_call_id, tool_name, full_result_json, model_visible_markdown, truncated, full_result_bytes, created_at FROM tool_result_artifacts
WHERE project_id = ?1
  AND session_id = ?2
ORDER BY created_at DESC
`

type ListToolResultArtifactsParams struct {
	ProjectID string         `json:"project_id"`
	SessionID sql.NullString `json:"session_id"`
}

func (q *Queries) ListToolResultArtifacts(ctx context.Context, arg ListToolResultArtifactsParams) ([]ToolResultArtifact, error) {
	rows, err := q.db.QueryContext(ctx, listToolResultArtifacts, arg.ProjectID, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ToolResultArtifact
	for rows.Next() {
		var i ToolResultArtifact
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SessionID,
			&i.ToolCallID,
			&i.ToolName,
			&i.FullResultJson,
			&i.ModelVisibleMarkdown,
			&i.Truncated,
			&i.FullResultBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listToolResultArtifactsByProject = `-- name: ListToolResultArtifactsByProject :many
SELECT id, project_id, session_id, tool_call_id, tool_name, full_result_json, model_visible_markdown, truncated, full_result_bytes, created_at FROM tool_result_artifacts
WHERE project_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListToolResultArtifactsByProject(ctx context.Context, projectID string) ([]ToolResultArtifact, error) {
	rows, err := q.db.QueryContext(ctx, listToolResultArtifactsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ToolResultArtifact
	for rows.Next() {
		var i ToolResultArtifact
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SessionID,
			&i.ToolCallID,
			&i.ToolName,
			&i.FullResultJson,
			&i.ModelVisibleMarkdown,
			&i.Truncated,
			&i.FullResultBytes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchAgentSession = `-- name: TouchAgentSession :exec
UPDATE agent_sessions
SET updated_at = ?1
WHERE project_id = ?2
  AND id = ?3
`

type TouchAgentSessionParams struct {
	UpdatedAt string `json:"updated_at"`
	ProjectID string `json:"project_id"`
	ID        string `json:"id"`
}

func (q *Queries) TouchAgentSession(ctx context.Context, arg TouchAgentSessionParams) error {
	_, err := q.db.ExecContext(ctx, touchAgentSession, arg.UpdatedAt, arg.ProjectID, arg.ID)
	return err
}

const updateGenerationCandidateStatus = `-- name: UpdateGenerationCandidateStatus :exec
UPDATE generation_candidates
SET status = ?1,
    updated_at = ?2
WHERE project_id = ?3
  AND id = ?4
`

type UpdateGenerationCandidateStatusParams struct {
	Status    string `json:"status"`
	UpdatedAt string `json:"updated_at"`
	ProjectID string `json:"project_id"`
	ID        string `json:"id"`
}

func (q *Queries) UpdateGenerationCandidateStatus(ctx context.Context, arg UpdateGenerationCandidateStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateGenerationCandidateStatus,
		arg.Status,
		arg.UpdatedAt,
		arg.ProjectID,
		arg.ID,
	)
	return err
}

const updateModelVariant = `-- name: UpdateModelVariant :exec
UPDATE model_variants
SET name = ?1,
    model = ?2,
    temperature = ?3,
    max_output_tokens = ?4,
    context_window_tokens = ?5,
    input_price_per_million = ?6,
    output_price_per_million = ?7,
    cache_read_price_per_million = ?8,
    cache_write_price_per_million = ?9,
    request_token_field = ?10,
    reasoning_format = ?11,
    compatibility_json = ?12,
    updated_at = ?13
WHERE model_variants.id = ?14
  AND provider_config_id IN (
    SELECT provider_configs.id FROM provider_configs
    WHERE provider_configs.author_id = ?15
  )
`

type UpdateModelVariantParams struct {
	Name                      string  `json:"name"`
	Model                     string  `json:"model"`
	Temperature               float64 `json:"temperature"`
	MaxOutputTokens           int64   `json:"max_output_tokens"`
	ContextWindowTokens       int64   `json:"context_window_tokens"`
	InputPricePerMillion      float64 `json:"input_price_per_million"`
	OutputPricePerMillion     float64 `json:"output_price_per_million"`
	CacheReadPricePerMillion  float64 `json:"cache_read_price_per_million"`
	CacheWritePricePerMillion float64 `json:"cache_write_price_per_million"`
	RequestTokenField         string  `json:"request_token_field"`
	ReasoningFormat           string  `json:"reasoning_format"`
	CompatibilityJson         string  `json:"compatibility_json"`
	UpdatedAt                 string  `json:"updated_at"`
	ID                        string  `json:"id"`
	AuthorID                  string  `json:"author_id"`
}

func (q *Queries) UpdateModelVariant(ctx context.Context, arg UpdateModelVariantParams) error {
	_, err := q.db.ExecContext(ctx, updateModelVariant,
		arg.Name,
		arg.Model,
		arg.Temperature,
		arg.MaxOutputTokens,
		arg.ContextWindowTokens,
		arg.InputPricePerMillion,
		arg.OutputPricePerMillion,
		arg.CacheReadPricePerMillion,
		arg.CacheWritePricePerMillion,
		arg.RequestTokenField,
		arg.ReasoningFormat,
		arg.CompatibilityJson,
		arg.UpdatedAt,
		arg.ID,
		arg.AuthorID,
	)
	return err
}

const updateProviderConfig = `-- name: UpdateProviderConfig :exec
UPDATE provider_configs
SET base_url = ?1,
    api_key_encrypted = ?2,
    updated_at = ?3
WHERE id = ?4
  AND author_id = ?5
`

type UpdateProviderConfigParams struct {
	BaseUrl         string `json:"base_url"`
	ApiKeyEncrypted string `json:"api_key_encrypted"`
	UpdatedAt       string `json:"updated_at"`
	ID              string `json:"id"`
	AuthorID        string `json:"author_id"`
}

func (q *Queries) UpdateProviderConfig(ctx context.Context, arg UpdateProviderConfigParams) error {
	_, err := q.db.ExecContext(ctx, updateProviderConfig,
		arg.BaseUrl,
		arg.ApiKeyEncrypted,
		arg.UpdatedAt,
		arg.ID,
		arg.AuthorID,
	)
	return err
}

const upsertPromptProfile = `-- name: UpsertPromptProfile :exec
INSERT INTO prompt_profiles (
  id, project_id, genre, tense, pov, voice, instructions_markdown,
  prompt_record_retention_days, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(project_id) DO UPDATE SET
  genre = excluded.genre,
  tense = excluded.tense,
  pov = excluded.pov,
  voice = excluded.voice,
  instructions_markdown = excluded.instructions_markdown,
  prompt_record_retention_days = excluded.prompt_record_retention_days,
  updated_at = excluded.updated_at
`

type UpsertPromptProfileParams struct {
	ID                        string `json:"id"`
	ProjectID                 string `json:"project_id"`
	Genre                     string `json:"genre"`
	Tense                     string `json:"tense"`
	Pov                       string `json:"pov"`
	Voice                     string `json:"voice"`
	InstructionsMarkdown      string `json:"instructions_markdown"`
	PromptRecordRetentionDays int64  `json:"prompt_record_retention_days"`
	CreatedAt                 string `json:"created_at"`
	UpdatedAt                 string `json:"updated_at"`
}

func (q *Queries) UpsertPromptProfile(ctx context.Context, arg UpsertPromptProfileParams) error {
	_, err := q.db.ExecContext(ctx, upsertPromptProfile,
		arg.ID,
		arg.ProjectID,
		arg.Genre,
		arg.Tense,
		arg.Pov,
		arg.Voice,
		arg.InstructionsMarkdown,
		arg.PromptRecordRetentionDays,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
