// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package store

import (
	"context"
)

const createAuthor = `-- name: CreateAuthor :exec
INSERT INTO authors (id, email, password_hash, created_at)
VALUES (?, ?, ?, ?)
`

type CreateAuthorParams struct {
	ID           string `json:"id"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	CreatedAt    string `json:"created_at"`
}

func (q *Queries) CreateAuthor(ctx context.Context, arg CreateAuthorParams) error {
	_, err := q.db.ExecContext(ctx, createAuthor,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.CreatedAt,
	)
	return err
}

const getAuthorByEmail = `-- name: GetAuthorByEmail :one
SELECT id, email, password_hash, created_at FROM authors
WHERE email = ?
`

func (q *Queries) GetAuthorByEmail(ctx context.Context, email string) (Author, error) {
	row := q.db.QueryRowContext(ctx, getAuthorByEmail, email)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}
