// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql"
)

type AttachedNote struct {
	ID             string         `json:"id"`
	ProjectID      string         `json:"project_id"`
	ContentItemID  sql.NullString `json:"content_item_id"`
	SelectionStart sql.NullInt64  `json:"selection_start"`
	SelectionEnd   sql.NullInt64  `json:"selection_end"`
	Title          string         `json:"title"`
	BodyMarkdown   string         `json:"body_markdown"`
	Source         string         `json:"source"`
	CreatedAt      string         `json:"created_at"`
	UpdatedAt      string         `json:"updated_at"`
}

type Author struct {
	ID           string `json:"id"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	CreatedAt    string `json:"created_at"`
}

type ContentItem struct {
	ID              string `json:"id"`
	ProjectID       string `json:"project_id"`
	Kind            string `json:"kind"`
	Title           string `json:"title"`
	Slug            string `json:"slug"`
	BodyMarkdown    string `json:"body_markdown"`
	MetadataJson    string `json:"metadata_json"`
	SortOrder       int64  `json:"sort_order"`
	CurrentRevision int64  `json:"current_revision"`
	CreatedAt       string `json:"created_at"`
	UpdatedAt       string `json:"updated_at"`
}

type ContentSearch struct {
	Title        string `json:"title"`
	BodyMarkdown string `json:"body_markdown"`
}

type EntryRelation struct {
	ID           string         `json:"id"`
	ProjectID    string         `json:"project_id"`
	SourceItemID string         `json:"source_item_id"`
	TargetItemID sql.NullString `json:"target_item_id"`
	TargetTitle  string         `json:"target_title"`
	RelationType string         `json:"relation_type"`
	CreatedAt    string         `json:"created_at"`
}

type EntrySection struct {
	ID            string `json:"id"`
	ContentItemID string `json:"content_item_id"`
	Heading       string `json:"heading"`
	BodyMarkdown  string `json:"body_markdown"`
	SortOrder     int64  `json:"sort_order"`
}

type Revision struct {
	ID             string `json:"id"`
	ContentItemID  string `json:"content_item_id"`
	RevisionNumber int64  `json:"revision_number"`
	BodyMarkdown   string `json:"body_markdown"`
	MetadataJson   string `json:"metadata_json"`
	Reason         string `json:"reason"`
	CreatedBy      string `json:"created_by"`
	CreatedAt      string `json:"created_at"`
}

type StoryProject struct {
	ID        string `json:"id"`
	AuthorID  string `json:"author_id"`
	Title     string `json:"title"`
	Slug      string `json:"slug"`
	Language  string `json:"language"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}
