// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project_core.sql

package store

import (
	"context"
	"database/sql"
)

const createContentItem = `-- name: CreateContentItem :exec
INSERT INTO content_items (
  id, project_id, kind, title, slug, body_markdown, metadata_json,
  sort_order, current_revision, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateContentItemParams struct {
	ID              string `json:"id"`
	ProjectID       string `json:"project_id"`
	Kind            string `json:"kind"`
	Title           string `json:"title"`
	Slug            string `json:"slug"`
	BodyMarkdown    string `json:"body_markdown"`
	MetadataJson    string `json:"metadata_json"`
	SortOrder       int64  `json:"sort_order"`
	CurrentRevision int64  `json:"current_revision"`
	CreatedAt       string `json:"created_at"`
	UpdatedAt       string `json:"updated_at"`
}

func (q *Queries) CreateContentItem(ctx context.Context, arg CreateContentItemParams) error {
	_, err := q.db.ExecContext(ctx, createContentItem,
		arg.ID,
		arg.ProjectID,
		arg.Kind,
		arg.Title,
		arg.Slug,
		arg.BodyMarkdown,
		arg.MetadataJson,
		arg.SortOrder,
		arg.CurrentRevision,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createEntryRelation = `-- name: CreateEntryRelation :exec
INSERT INTO entry_relations (
  id, project_id, source_item_id, target_item_id, target_title, relation_type, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateEntryRelationParams struct {
	ID           string         `json:"id"`
	ProjectID    string         `json:"project_id"`
	SourceItemID string         `json:"source_item_id"`
	TargetItemID sql.NullString `json:"target_item_id"`
	TargetTitle  string         `json:"target_title"`
	RelationType string         `json:"relation_type"`
	CreatedAt    string         `json:"created_at"`
}

func (q *Queries) CreateEntryRelation(ctx context.Context, arg CreateEntryRelationParams) error {
	_, err := q.db.ExecContext(ctx, createEntryRelation,
		arg.ID,
		arg.ProjectID,
		arg.SourceItemID,
		arg.TargetItemID,
		arg.TargetTitle,
		arg.RelationType,
		arg.CreatedAt,
	)
	return err
}

const createEntrySection = `-- name: CreateEntrySection :exec
INSERT INTO entry_sections (id, content_item_id, heading, body_markdown, sort_order)
VALUES (?, ?, ?, ?, ?)
`

type CreateEntrySectionParams struct {
	ID            string `json:"id"`
	ContentItemID string `json:"content_item_id"`
	Heading       string `json:"heading"`
	BodyMarkdown  string `json:"body_markdown"`
	SortOrder     int64  `json:"sort_order"`
}

func (q *Queries) CreateEntrySection(ctx context.Context, arg CreateEntrySectionParams) error {
	_, err := q.db.ExecContext(ctx, createEntrySection,
		arg.ID,
		arg.ContentItemID,
		arg.Heading,
		arg.BodyMarkdown,
		arg.SortOrder,
	)
	return err
}

const createRevision = `-- name: CreateRevision :exec
INSERT INTO revisions (
  id, content_item_id, revision_number, body_markdown, metadata_json,
  reason, created_by, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateRevisionParams struct {
	ID             string `json:"id"`
	ContentItemID  string `json:"content_item_id"`
	RevisionNumber int64  `json:"revision_number"`
	BodyMarkdown   string `json:"body_markdown"`
	MetadataJson   string `json:"metadata_json"`
	Reason         string `json:"reason"`
	CreatedBy      string `json:"created_by"`
	CreatedAt      string `json:"created_at"`
}

func (q *Queries) CreateRevision(ctx context.Context, arg CreateRevisionParams) error {
	_, err := q.db.ExecContext(ctx, createRevision,
		arg.ID,
		arg.ContentItemID,
		arg.RevisionNumber,
		arg.BodyMarkdown,
		arg.MetadataJson,
		arg.Reason,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const createStoryProject = `-- name: CreateStoryProject :exec
INSERT INTO story_projects (id, author_id, title, slug, language, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateStoryProjectParams struct {
	ID        string `json:"id"`
	AuthorID  string `json:"author_id"`
	Title     string `json:"title"`
	Slug      string `json:"slug"`
	Language  string `json:"language"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}

func (q *Queries) CreateStoryProject(ctx context.Context, arg CreateStoryProjectParams) error {
	_, err := q.db.ExecContext(ctx, createStoryProject,
		arg.ID,
		arg.AuthorID,
		arg.Title,
		arg.Slug,
		arg.Language,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getContentItem = `-- name: GetContentItem :one
SELECT id, project_id, kind, title, slug, body_markdown, metadata_json, sort_order, current_revision, created_at, updated_at FROM content_items
WHERE id = ? AND project_id = ?
`

type GetContentItemParams struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) GetContentItem(ctx context.Context, arg GetContentItemParams) (ContentItem, error) {
	row := q.db.QueryRowContext(ctx, getContentItem, arg.ID, arg.ProjectID)
	var i ContentItem
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Kind,
		&i.Title,
		&i.Slug,
		&i.BodyMarkdown,
		&i.MetadataJson,
		&i.SortOrder,
		&i.CurrentRevision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStoryProject = `-- name: GetStoryProject :one
SELECT id, author_id, title, slug, language, created_at, updated_at FROM story_projects
WHERE id = ? AND author_id = ?
`

type GetStoryProjectParams struct {
	ID       string `json:"id"`
	AuthorID string `json:"author_id"`
}

func (q *Queries) GetStoryProject(ctx context.Context, arg GetStoryProjectParams) (StoryProject, error) {
	row := q.db.QueryRowContext(ctx, getStoryProject, arg.ID, arg.AuthorID)
	var i StoryProject
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Title,
		&i.Slug,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listContentItems = `-- name: ListContentItems :many
SELECT id, project_id, kind, title, slug, body_markdown, metadata_json, sort_order, current_revision, created_at, updated_at FROM content_items
WHERE project_id = ? AND kind = ?
ORDER BY sort_order ASC, title ASC
`

type ListContentItemsParams struct {
	ProjectID string `json:"project_id"`
	Kind      string `json:"kind"`
}

func (q *Queries) ListContentItems(ctx context.Context, arg ListContentItemsParams) ([]ContentItem, error) {
	rows, err := q.db.QueryContext(ctx, listContentItems, arg.ProjectID, arg.Kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContentItem
	for rows.Next() {
		var i ContentItem
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Kind,
			&i.Title,
			&i.Slug,
			&i.BodyMarkdown,
			&i.MetadataJson,
			&i.SortOrder,
			&i.CurrentRevision,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntryRelations = `-- name: ListEntryRelations :many
SELECT id, project_id, source_item_id, target_item_id, target_title, relation_type, created_at FROM entry_relations
WHERE project_id = ? AND source_item_id = ?
ORDER BY target_title ASC
`

type ListEntryRelationsParams struct {
	ProjectID    string `json:"project_id"`
	SourceItemID string `json:"source_item_id"`
}

func (q *Queries) ListEntryRelations(ctx context.Context, arg ListEntryRelationsParams) ([]EntryRelation, error) {
	rows, err := q.db.QueryContext(ctx, listEntryRelations, arg.ProjectID, arg.SourceItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntryRelation
	for rows.Next() {
		var i EntryRelation
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SourceItemID,
			&i.TargetItemID,
			&i.TargetTitle,
			&i.RelationType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntrySections = `-- name: ListEntrySections :many
SELECT id, content_item_id, heading, body_markdown, sort_order FROM entry_sections
WHERE content_item_id = ?
ORDER BY sort_order ASC
`

func (q *Queries) ListEntrySections(ctx context.Context, contentItemID string) ([]EntrySection, error) {
	rows, err := q.db.QueryContext(ctx, listEntrySections, contentItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntrySection
	for rows.Next() {
		var i EntrySection
		if err := rows.Scan(
			&i.ID,
			&i.ContentItemID,
			&i.Heading,
			&i.BodyMarkdown,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRevisions = `-- name: ListRevisions :many
SELECT revisions.id, revisions.content_item_id, revisions.revision_number, revisions.body_markdown, revisions.metadata_json, revisions.reason, revisions.created_by, revisions.created_at
FROM revisions
JOIN content_items ON content_items.id = revisions.content_item_id
WHERE revisions.content_item_id = ?1
  AND content_items.project_id = ?2
ORDER BY revision_number DESC
`

type ListRevisionsParams struct {
	ContentItemID string `json:"content_item_id"`
	ProjectID     string `json:"project_id"`
}

func (q *Queries) ListRevisions(ctx context.Context, arg ListRevisionsParams) ([]Revision, error) {
	rows, err := q.db.QueryContext(ctx, listRevisions, arg.ContentItemID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Revision
	for rows.Next() {
		var i Revision
		if err := rows.Scan(
			&i.ID,
			&i.ContentItemID,
			&i.RevisionNumber,
			&i.BodyMarkdown,
			&i.MetadataJson,
			&i.Reason,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStoryProjects = `-- name: ListStoryProjects :many
SELECT id, author_id, title, slug, language, created_at, updated_at FROM story_projects
WHERE author_id = ?
ORDER BY updated_at DESC, title ASC
`

func (q *Queries) ListStoryProjects(ctx context.Context, authorID string) ([]StoryProject, error) {
	rows, err := q.db.QueryContext(ctx, listStoryProjects, authorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StoryProject
	for rows.Next() {
		var i StoryProject
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Title,
			&i.Slug,
			&i.Language,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchContent = `-- name: SearchContent :many
SELECT content_items.id, content_items.project_id, content_items.kind, content_items.title, content_items.slug, content_items.body_markdown, content_items.metadata_json, content_items.sort_order, content_items.current_revision, content_items.created_at, content_items.updated_at
FROM content_search(CAST(?1 AS TEXT))
JOIN content_items ON content_items.rowid = content_search.rowid
WHERE content_items.project_id = ?2
ORDER BY rank
LIMIT ?3
`

type SearchContentParams struct {
	Query     string `json:"query"`
	ProjectID string `json:"project_id"`
	Limit     int64  `json:"limit"`
}

func (q *Queries) SearchContent(ctx context.Context, arg SearchContentParams) ([]ContentItem, error) {
	rows, err := q.db.QueryContext(ctx, searchContent, arg.Query, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContentItem
	for rows.Next() {
		var i ContentItem
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Kind,
			&i.Title,
			&i.Slug,
			&i.BodyMarkdown,
			&i.MetadataJson,
			&i.SortOrder,
			&i.CurrentRevision,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContentItemBody = `-- name: UpdateContentItemBody :execrows
UPDATE content_items
SET body_markdown = ?1,
    metadata_json = ?2,
    current_revision = ?3,
    updated_at = ?4
WHERE id = ?5
  AND project_id = ?6
  AND current_revision = ?7
`

type UpdateContentItemBodyParams struct {
	BodyMarkdown     string `json:"body_markdown"`
	MetadataJson     string `json:"metadata_json"`
	NextRevision     int64  `json:"next_revision"`
	UpdatedAt        string `json:"updated_at"`
	ID               string `json:"id"`
	ProjectID        string `json:"project_id"`
	ExpectedRevision int64  `json:"expected_revision"`
}

func (q *Queries) UpdateContentItemBody(ctx context.Context, arg UpdateContentItemBodyParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateContentItemBody,
		arg.BodyMarkdown,
		arg.MetadataJson,
		arg.NextRevision,
		arg.UpdatedAt,
		arg.ID,
		arg.ProjectID,
		arg.ExpectedRevision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
