// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	CreateContentItem(ctx context.Context, arg CreateContentItemParams) error
	CreateEntryRelation(ctx context.Context, arg CreateEntryRelationParams) error
	CreateEntrySection(ctx context.Context, arg CreateEntrySectionParams) error
	CreateRevision(ctx context.Context, arg CreateRevisionParams) error
	CreateStoryProject(ctx context.Context, arg CreateStoryProjectParams) error
	GetContentItem(ctx context.Context, arg GetContentItemParams) (ContentItem, error)
	GetStoryProject(ctx context.Context, arg GetStoryProjectParams) (StoryProject, error)
	GetStoryProjectByID(ctx context.Context, id string) (StoryProject, error)
	ListContentItems(ctx context.Context, arg ListContentItemsParams) ([]ContentItem, error)
	ListEntryRelations(ctx context.Context, arg ListEntryRelationsParams) ([]EntryRelation, error)
	ListEntrySections(ctx context.Context, contentItemID string) ([]EntrySection, error)
	ListProjectContentItems(ctx context.Context, projectID string) ([]ContentItem, error)
	ListRevisions(ctx context.Context, arg ListRevisionsParams) ([]Revision, error)
	ListStoryProjects(ctx context.Context, authorID string) ([]StoryProject, error)
	SearchContent(ctx context.Context, arg SearchContentParams) ([]ContentItem, error)
	UpdateContentItemBody(ctx context.Context, arg UpdateContentItemBodyParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
