// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	AddSessionSkill(ctx context.Context, arg AddSessionSkillParams) (int64, error)
	CountSkillsByProject(ctx context.Context, projectID string) (int64, error)
	CreateActivityEvent(ctx context.Context, arg CreateActivityEventParams) error
	CreateAgentMessage(ctx context.Context, arg CreateAgentMessageParams) error
	CreateAgentMessageForProject(ctx context.Context, arg CreateAgentMessageForProjectParams) (int64, error)
	CreateAgentSession(ctx context.Context, arg CreateAgentSessionParams) error
	CreateAttachedNote(ctx context.Context, arg CreateAttachedNoteParams) error
	CreateContentItem(ctx context.Context, arg CreateContentItemParams) error
	CreateEntryRelation(ctx context.Context, arg CreateEntryRelationParams) error
	CreateEntrySection(ctx context.Context, arg CreateEntrySectionParams) error
	CreateGenerationCandidate(ctx context.Context, arg CreateGenerationCandidateParams) error
	CreateModelVariant(ctx context.Context, arg CreateModelVariantParams) error
	CreatePromptContextSnapshot(ctx context.Context, arg CreatePromptContextSnapshotParams) error
	CreatePromptRecord(ctx context.Context, arg CreatePromptRecordParams) error
	CreateProviderConfig(ctx context.Context, arg CreateProviderConfigParams) error
	CreateRevision(ctx context.Context, arg CreateRevisionParams) error
	CreateSkillFile(ctx context.Context, arg CreateSkillFileParams) error
	CreateSkillRoutingHint(ctx context.Context, arg CreateSkillRoutingHintParams) error
	CreateStoryProject(ctx context.Context, arg CreateStoryProjectParams) error
	CreateToolResultArtifact(ctx context.Context, arg CreateToolResultArtifactParams) error
	DeleteExpiredPromptRecords(ctx context.Context, arg DeleteExpiredPromptRecordsParams) (int64, error)
	DeleteModelVariant(ctx context.Context, arg DeleteModelVariantParams) error
	DeletePromptRecordsByProject(ctx context.Context, projectID string) (int64, error)
	DeleteProviderConfig(ctx context.Context, arg DeleteProviderConfigParams) error
	DeleteSkillFiles(ctx context.Context, skillID string) error
	DeleteSkillRoutingHints(ctx context.Context, skillID string) error
	GetAgentSession(ctx context.Context, arg GetAgentSessionParams) (AgentSession, error)
	GetContentItem(ctx context.Context, arg GetContentItemParams) (ContentItem, error)
	GetEntrySection(ctx context.Context, arg GetEntrySectionParams) (EntrySection, error)
	GetGenerationCandidate(ctx context.Context, arg GetGenerationCandidateParams) (GenerationCandidate, error)
	GetModelVariant(ctx context.Context, arg GetModelVariantParams) (ModelVariant, error)
	GetModelVariantForProject(ctx context.Context, arg GetModelVariantForProjectParams) (ModelVariant, error)
	GetPromptProfile(ctx context.Context, projectID string) (PromptProfile, error)
	GetProviderConfig(ctx context.Context, arg GetProviderConfigParams) (ProviderConfig, error)
	GetProviderConfigForProjectModel(ctx context.Context, arg GetProviderConfigForProjectModelParams) (ProviderConfig, error)
	GetSkillByProjectID(ctx context.Context, arg GetSkillByProjectIDParams) (Skill, error)
	GetSkillByProjectName(ctx context.Context, arg GetSkillByProjectNameParams) (Skill, error)
	GetSkillFile(ctx context.Context, arg GetSkillFileParams) (SkillFile, error)
	GetStoryProject(ctx context.Context, arg GetStoryProjectParams) (StoryProject, error)
	GetStoryProjectByID(ctx context.Context, id string) (StoryProject, error)
	ListActivityEvents(ctx context.Context, arg ListActivityEventsParams) ([]ActivityEvent, error)
	ListAgentMessages(ctx context.Context, sessionID string) ([]AgentMessage, error)
	ListAgentMessagesForProject(ctx context.Context, arg ListAgentMessagesForProjectParams) ([]AgentMessage, error)
	ListAgentSessions(ctx context.Context, arg ListAgentSessionsParams) ([]AgentSession, error)
	ListContentItems(ctx context.Context, arg ListContentItemsParams) ([]ContentItem, error)
	ListEntryRelations(ctx context.Context, arg ListEntryRelationsParams) ([]EntryRelation, error)
	ListEntrySections(ctx context.Context, arg ListEntrySectionsParams) ([]EntrySection, error)
	ListGenerationCandidates(ctx context.Context, arg ListGenerationCandidatesParams) ([]GenerationCandidate, error)
	ListModelVariantsByAuthor(ctx context.Context, authorID string) ([]ModelVariant, error)
	ListModelVariantsByProvider(ctx context.Context, arg ListModelVariantsByProviderParams) ([]ModelVariant, error)
	ListProjectContentItems(ctx context.Context, projectID string) ([]ContentItem, error)
	ListPromptContextSnapshots(ctx context.Context, promptRecordID string) ([]PromptContextSnapshot, error)
	ListPromptRecords(ctx context.Context, arg ListPromptRecordsParams) ([]PromptRecord, error)
	ListProviderConfigs(ctx context.Context, authorID string) ([]ProviderConfig, error)
	ListRevisions(ctx context.Context, arg ListRevisionsParams) ([]Revision, error)
	ListRoutableSkills(ctx context.Context, arg ListRoutableSkillsParams) ([]Skill, error)
	ListSessionSkillIDs(ctx context.Context, arg ListSessionSkillIDsParams) ([]string, error)
	ListSessionSkills(ctx context.Context, arg ListSessionSkillsParams) ([]Skill, error)
	ListSkillFiles(ctx context.Context, skillID string) ([]SkillFile, error)
	ListSkillRoutingHints(ctx context.Context, skillID string) ([]SkillRoutingHint, error)
	ListSkillsByProject(ctx context.Context, projectID string) ([]Skill, error)
	ListStoryProjects(ctx context.Context, authorID string) ([]StoryProject, error)
	ListToolResultArtifacts(ctx context.Context, arg ListToolResultArtifactsParams) ([]ToolResultArtifact, error)
	ListToolResultArtifactsByProject(ctx context.Context, projectID string) ([]ToolResultArtifact, error)
	ReplaceSessionSkillsDelete(ctx context.Context, sessionID string) error
	SearchContent(ctx context.Context, arg SearchContentParams) ([]ContentItem, error)
	SearchContentCandidates(ctx context.Context, arg SearchContentCandidatesParams) ([]ContentItem, error)
	TouchAgentSession(ctx context.Context, arg TouchAgentSessionParams) error
	UpdateContentItemBody(ctx context.Context, arg UpdateContentItemBodyParams) (int64, error)
	UpdateEntrySectionBody(ctx context.Context, arg UpdateEntrySectionBodyParams) (int64, error)
	UpdateGenerationCandidateStatus(ctx context.Context, arg UpdateGenerationCandidateStatusParams) error
	UpdateGenerationCandidateStatusIfStatus(ctx context.Context, arg UpdateGenerationCandidateStatusIfStatusParams) (int64, error)
	UpdateModelVariant(ctx context.Context, arg UpdateModelVariantParams) error
	UpdateProviderConfig(ctx context.Context, arg UpdateProviderConfigParams) error
	UpsertPromptProfile(ctx context.Context, arg UpsertPromptProfileParams) error
	UpsertSkill(ctx context.Context, arg UpsertSkillParams) error
}

var _ Querier = (*Queries)(nil)
