// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: skill_core.sql

package store

import (
	"context"
)

const addSessionSkill = `-- name: AddSessionSkill :execrows
INSERT INTO agent_session_skills (project_id, session_id, skill_id, selected_at)
SELECT ?1, agent_sessions.id, skills.id, ?2
FROM agent_sessions
JOIN skills ON skills.id = ?3
WHERE agent_sessions.id = ?4
  AND agent_sessions.project_id = ?1
  AND skills.project_id = ?1
`

type AddSessionSkillParams struct {
	ProjectID  string `json:"project_id"`
	SelectedAt string `json:"selected_at"`
	SkillID    string `json:"skill_id"`
	SessionID  string `json:"session_id"`
}

func (q *Queries) AddSessionSkill(ctx context.Context, arg AddSessionSkillParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, addSessionSkill,
		arg.ProjectID,
		arg.SelectedAt,
		arg.SkillID,
		arg.SessionID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countSkillsByProject = `-- name: CountSkillsByProject :one
SELECT COUNT(*) FROM skills
WHERE project_id = ?
`

func (q *Queries) CountSkillsByProject(ctx context.Context, projectID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSkillsByProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSkillFile = `-- name: CreateSkillFile :exec
INSERT INTO skill_files (
  id, skill_id, relative_path, purpose, media_type, body_text, bytes, script_disabled, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateSkillFileParams struct {
	ID             string `json:"id"`
	SkillID        string `json:"skill_id"`
	RelativePath   string `json:"relative_path"`
	Purpose        string `json:"purpose"`
	MediaType      string `json:"media_type"`
	BodyText       string `json:"body_text"`
	Bytes          int64  `json:"bytes"`
	ScriptDisabled int64  `json:"script_disabled"`
	CreatedAt      string `json:"created_at"`
}

func (q *Queries) CreateSkillFile(ctx context.Context, arg CreateSkillFileParams) error {
	_, err := q.db.ExecContext(ctx, createSkillFile,
		arg.ID,
		arg.SkillID,
		arg.RelativePath,
		arg.Purpose,
		arg.MediaType,
		arg.BodyText,
		arg.Bytes,
		arg.ScriptDisabled,
		arg.CreatedAt,
	)
	return err
}

const createSkillRoutingHint = `-- name: CreateSkillRoutingHint :exec
INSERT INTO skill_routing_hints (
  id, skill_id, action_kind, content_kind, tag, priority, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateSkillRoutingHintParams struct {
	ID          string `json:"id"`
	SkillID     string `json:"skill_id"`
	ActionKind  string `json:"action_kind"`
	ContentKind string `json:"content_kind"`
	Tag         string `json:"tag"`
	Priority    int64  `json:"priority"`
	CreatedAt   string `json:"created_at"`
}

func (q *Queries) CreateSkillRoutingHint(ctx context.Context, arg CreateSkillRoutingHintParams) error {
	_, err := q.db.ExecContext(ctx, createSkillRoutingHint,
		arg.ID,
		arg.SkillID,
		arg.ActionKind,
		arg.ContentKind,
		arg.Tag,
		arg.Priority,
		arg.CreatedAt,
	)
	return err
}

const deleteSkillFiles = `-- name: DeleteSkillFiles :exec
DELETE FROM skill_files
WHERE skill_id = ?
`

func (q *Queries) DeleteSkillFiles(ctx context.Context, skillID string) error {
	_, err := q.db.ExecContext(ctx, deleteSkillFiles, skillID)
	return err
}

const deleteSkillRoutingHints = `-- name: DeleteSkillRoutingHints :exec
DELETE FROM skill_routing_hints
WHERE skill_id = ?
`

func (q *Queries) DeleteSkillRoutingHints(ctx context.Context, skillID string) error {
	_, err := q.db.ExecContext(ctx, deleteSkillRoutingHints, skillID)
	return err
}

const getSkillByProjectID = `-- name: GetSkillByProjectID :one
SELECT id, project_id, name, display_name, description, instructions_markdown, source_type, source_label, script_count, scripts_disabled, metadata_json, installed_at, updated_at FROM skills
WHERE project_id = ? AND id = ?
`

type GetSkillByProjectIDParams struct {
	ProjectID string `json:"project_id"`
	ID        string `json:"id"`
}

func (q *Queries) GetSkillByProjectID(ctx context.Context, arg GetSkillByProjectIDParams) (Skill, error) {
	row := q.db.QueryRowContext(ctx, getSkillByProjectID, arg.ProjectID, arg.ID)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.InstructionsMarkdown,
		&i.SourceType,
		&i.SourceLabel,
		&i.ScriptCount,
		&i.ScriptsDisabled,
		&i.MetadataJson,
		&i.InstalledAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSkillByProjectName = `-- name: GetSkillByProjectName :one
SELECT id, project_id, name, display_name, description, instructions_markdown, source_type, source_label, script_count, scripts_disabled, metadata_json, installed_at, updated_at FROM skills
WHERE project_id = ? AND name = ?
`

type GetSkillByProjectNameParams struct {
	ProjectID string `json:"project_id"`
	Name      string `json:"name"`
}

func (q *Queries) GetSkillByProjectName(ctx context.Context, arg GetSkillByProjectNameParams) (Skill, error) {
	row := q.db.QueryRowContext(ctx, getSkillByProjectName, arg.ProjectID, arg.Name)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.InstructionsMarkdown,
		&i.SourceType,
		&i.SourceLabel,
		&i.ScriptCount,
		&i.ScriptsDisabled,
		&i.MetadataJson,
		&i.InstalledAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSkillFile = `-- name: GetSkillFile :one
SELECT skill_files.id, skill_files.skill_id, skill_files.relative_path, skill_files.purpose, skill_files.media_type, skill_files.body_text, skill_files.bytes, skill_files.script_disabled, skill_files.created_at
FROM skill_files
JOIN skills ON skills.id = skill_files.skill_id
WHERE skills.project_id = ?1
  AND skill_files.skill_id = ?2
  AND skill_files.relative_path = ?3
`

type GetSkillFileParams struct {
	ProjectID    string `json:"project_id"`
	SkillID      string `json:"skill_id"`
	RelativePath string `json:"relative_path"`
}

func (q *Queries) GetSkillFile(ctx context.Context, arg GetSkillFileParams) (SkillFile, error) {
	row := q.db.QueryRowContext(ctx, getSkillFile, arg.ProjectID, arg.SkillID, arg.RelativePath)
	var i SkillFile
	err := row.Scan(
		&i.ID,
		&i.SkillID,
		&i.RelativePath,
		&i.Purpose,
		&i.MediaType,
		&i.BodyText,
		&i.Bytes,
		&i.ScriptDisabled,
		&i.CreatedAt,
	)
	return i, err
}

const listRoutableSkills = `-- name: ListRoutableSkills :many
SELECT DISTINCT skills.id, skills.project_id, skills.name, skills.display_name, skills.description, skills.instructions_markdown, skills.source_type, skills.source_label, skills.script_count, skills.scripts_disabled, skills.metadata_json, skills.installed_at, skills.updated_at
FROM skills
LEFT JOIN skill_routing_hints ON skill_routing_hints.skill_id = skills.id
WHERE skills.project_id = ?1
  AND (
    skill_routing_hints.id IS NULL
    OR skill_routing_hints.action_kind = ''
    OR skill_routing_hints.action_kind = ?2
  )
  AND (
    skill_routing_hints.id IS NULL
    OR skill_routing_hints.content_kind = ''
    OR skill_routing_hints.content_kind = ?3
  )
ORDER BY skills.display_name ASC, skills.name ASC
`

type ListRoutableSkillsParams struct {
	ProjectID   string `json:"project_id"`
	ActionKind  string `json:"action_kind"`
	ContentKind string `json:"content_kind"`
}

func (q *Queries) ListRoutableSkills(ctx context.Context, arg ListRoutableSkillsParams) ([]Skill, error) {
	rows, err := q.db.QueryContext(ctx, listRoutableSkills, arg.ProjectID, arg.ActionKind, arg.ContentKind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Skill
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.InstructionsMarkdown,
			&i.SourceType,
			&i.SourceLabel,
			&i.ScriptCount,
			&i.ScriptsDisabled,
			&i.MetadataJson,
			&i.InstalledAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionSkillIDs = `-- name: ListSessionSkillIDs :many
SELECT skills.id
FROM agent_session_skills
JOIN skills ON skills.id = agent_session_skills.skill_id
JOIN agent_sessions ON agent_sessions.id = agent_session_skills.session_id
WHERE agent_session_skills.session_id = ?1
  AND agent_sessions.project_id = ?2
  AND skills.project_id = agent_sessions.project_id
ORDER BY skills.display_name ASC, skills.name ASC
`

type ListSessionSkillIDsParams struct {
	SessionID string `json:"session_id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) ListSessionSkillIDs(ctx context.Context, arg ListSessionSkillIDsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listSessionSkillIDs, arg.SessionID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionSkills = `-- name: ListSessionSkills :many
SELECT skills.id, skills.project_id, skills.name, skills.display_name, skills.description, skills.instructions_markdown, skills.source_type, skills.source_label, skills.script_count, skills.scripts_disabled, skills.metadata_json, skills.installed_at, skills.updated_at
FROM agent_session_skills
JOIN skills ON skills.id = agent_session_skills.skill_id
JOIN agent_sessions ON agent_sessions.id = agent_session_skills.session_id
WHERE agent_session_skills.session_id = ?1
  AND agent_sessions.project_id = ?2
  AND skills.project_id = agent_sessions.project_id
ORDER BY skills.display_name ASC, skills.name ASC
`

type ListSessionSkillsParams struct {
	SessionID string `json:"session_id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) ListSessionSkills(ctx context.Context, arg ListSessionSkillsParams) ([]Skill, error) {
	rows, err := q.db.QueryContext(ctx, listSessionSkills, arg.SessionID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Skill
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.InstructionsMarkdown,
			&i.SourceType,
			&i.SourceLabel,
			&i.ScriptCount,
			&i.ScriptsDisabled,
			&i.MetadataJson,
			&i.InstalledAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillFiles = `-- name: ListSkillFiles :many
SELECT id, skill_id, relative_path, purpose, media_type, body_text, bytes, script_disabled, created_at FROM skill_files
WHERE skill_id = ?
ORDER BY relative_path ASC
`

func (q *Queries) ListSkillFiles(ctx context.Context, skillID string) ([]SkillFile, error) {
	rows, err := q.db.QueryContext(ctx, listSkillFiles, skillID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SkillFile
	for rows.Next() {
		var i SkillFile
		if err := rows.Scan(
			&i.ID,
			&i.SkillID,
			&i.RelativePath,
			&i.Purpose,
			&i.MediaType,
			&i.BodyText,
			&i.Bytes,
			&i.ScriptDisabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillRoutingHints = `-- name: ListSkillRoutingHints :many
SELECT id, skill_id, action_kind, content_kind, tag, priority, created_at FROM skill_routing_hints
WHERE skill_id = ?
ORDER BY priority DESC, action_kind ASC, content_kind ASC, tag ASC
`

func (q *Queries) ListSkillRoutingHints(ctx context.Context, skillID string) ([]SkillRoutingHint, error) {
	rows, err := q.db.QueryContext(ctx, listSkillRoutingHints, skillID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SkillRoutingHint
	for rows.Next() {
		var i SkillRoutingHint
		if err := rows.Scan(
			&i.ID,
			&i.SkillID,
			&i.ActionKind,
			&i.ContentKind,
			&i.Tag,
			&i.Priority,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillsByProject = `-- name: ListSkillsByProject :many
SELECT id, project_id, name, display_name, description, instructions_markdown, source_type, source_label, script_count, scripts_disabled, metadata_json, installed_at, updated_at FROM skills
WHERE project_id = ?
ORDER BY display_name ASC, name ASC
`

func (q *Queries) ListSkillsByProject(ctx context.Context, projectID string) ([]Skill, error) {
	rows, err := q.db.QueryContext(ctx, listSkillsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Skill
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.InstructionsMarkdown,
			&i.SourceType,
			&i.SourceLabel,
			&i.ScriptCount,
			&i.ScriptsDisabled,
			&i.MetadataJson,
			&i.InstalledAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceSessionSkillsDelete = `-- name: ReplaceSessionSkillsDelete :exec
DELETE FROM agent_session_skills
WHERE session_id = ?
`

func (q *Queries) ReplaceSessionSkillsDelete(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, replaceSessionSkillsDelete, sessionID)
	return err
}

const upsertSkill = `-- name: UpsertSkill :exec
INSERT INTO skills (
  id, project_id, name, display_name, description, instructions_markdown,
  source_type, source_label, script_count, scripts_disabled, metadata_json,
  installed_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(project_id, name) DO UPDATE SET
  display_name = excluded.display_name,
  description = excluded.description,
  instructions_markdown = excluded.instructions_markdown,
  source_type = excluded.source_type,
  source_label = excluded.source_label,
  script_count = excluded.script_count,
  scripts_disabled = excluded.scripts_disabled,
  metadata_json = excluded.metadata_json,
  updated_at = excluded.updated_at
`

type UpsertSkillParams struct {
	ID                   string `json:"id"`
	ProjectID            string `json:"project_id"`
	Name                 string `json:"name"`
	DisplayName          string `json:"display_name"`
	Description          string `json:"description"`
	InstructionsMarkdown string `json:"instructions_markdown"`
	SourceType           string `json:"source_type"`
	SourceLabel          string `json:"source_label"`
	ScriptCount          int64  `json:"script_count"`
	ScriptsDisabled      int64  `json:"scripts_disabled"`
	MetadataJson         string `json:"metadata_json"`
	InstalledAt          string `json:"installed_at"`
	UpdatedAt            string `json:"updated_at"`
}

func (q *Queries) UpsertSkill(ctx context.Context, arg UpsertSkillParams) error {
	_, err := q.db.ExecContext(ctx, upsertSkill,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.DisplayName,
		arg.Description,
		arg.InstructionsMarkdown,
		arg.SourceType,
		arg.SourceLabel,
		arg.ScriptCount,
		arg.ScriptsDisabled,
		arg.MetadataJson,
		arg.InstalledAt,
		arg.UpdatedAt,
	)
	return err
}
