// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: skill_script_runtime.sql

package store

import (
	"context"
	"database/sql"
)

const createSkillScriptRun = `-- name: CreateSkillScriptRun :exec
INSERT INTO skill_script_runs (
  id, project_id, session_id, skill_id, skill_file_id, approval_id, tool_call_id,
  status, output_kind, input_json, output_json, stdout_text, stderr_text,
  exit_code, duration_ms, error_message, created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateSkillScriptRunParams struct {
	ID           string         `json:"id"`
	ProjectID    string         `json:"project_id"`
	SessionID    sql.NullString `json:"session_id"`
	SkillID      string         `json:"skill_id"`
	SkillFileID  string         `json:"skill_file_id"`
	ApprovalID   string         `json:"approval_id"`
	ToolCallID   string         `json:"tool_call_id"`
	Status       string         `json:"status"`
	OutputKind   string         `json:"output_kind"`
	InputJson    string         `json:"input_json"`
	OutputJson   string         `json:"output_json"`
	StdoutText   string         `json:"stdout_text"`
	StderrText   string         `json:"stderr_text"`
	ExitCode     int64          `json:"exit_code"`
	DurationMs   int64          `json:"duration_ms"`
	ErrorMessage string         `json:"error_message"`
	CreatedAt    string         `json:"created_at"`
}

func (q *Queries) CreateSkillScriptRun(ctx context.Context, arg CreateSkillScriptRunParams) error {
	_, err := q.db.ExecContext(ctx, createSkillScriptRun,
		arg.ID,
		arg.ProjectID,
		arg.SessionID,
		arg.SkillID,
		arg.SkillFileID,
		arg.ApprovalID,
		arg.ToolCallID,
		arg.Status,
		arg.OutputKind,
		arg.InputJson,
		arg.OutputJson,
		arg.StdoutText,
		arg.StderrText,
		arg.ExitCode,
		arg.DurationMs,
		arg.ErrorMessage,
		arg.CreatedAt,
	)
	return err
}

const getSkillScriptApprovalByFile = `-- name: GetSkillScriptApprovalByFile :one
SELECT id, project_id, skill_id, skill_file_id, audit_id, enabled, runtime_command, timeout_ms, max_stdout_bytes, max_stderr_bytes, allow_network, allow_project_files, approved_by, approved_at, updated_at FROM skill_script_approvals
WHERE project_id = ? AND skill_file_id = ?
`

type GetSkillScriptApprovalByFileParams struct {
	ProjectID   string `json:"project_id"`
	SkillFileID string `json:"skill_file_id"`
}

func (q *Queries) GetSkillScriptApprovalByFile(ctx context.Context, arg GetSkillScriptApprovalByFileParams) (SkillScriptApproval, error) {
	row := q.db.QueryRowContext(ctx, getSkillScriptApprovalByFile, arg.ProjectID, arg.SkillFileID)
	var i SkillScriptApproval
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SkillID,
		&i.SkillFileID,
		&i.AuditID,
		&i.Enabled,
		&i.RuntimeCommand,
		&i.TimeoutMs,
		&i.MaxStdoutBytes,
		&i.MaxStderrBytes,
		&i.AllowNetwork,
		&i.AllowProjectFiles,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSkillScriptAuditByFile = `-- name: GetSkillScriptAuditByFile :one
SELECT id, project_id, skill_id, skill_file_id, relative_path, runtime, destructive_operations, filesystem_access, network_access, external_dependencies, expected_inputs_json, expected_outputs_json, risk_notes, recommendation, audited_at FROM skill_script_audits
WHERE project_id = ? AND skill_file_id = ?
`

type GetSkillScriptAuditByFileParams struct {
	ProjectID   string `json:"project_id"`
	SkillFileID string `json:"skill_file_id"`
}

func (q *Queries) GetSkillScriptAuditByFile(ctx context.Context, arg GetSkillScriptAuditByFileParams) (SkillScriptAudit, error) {
	row := q.db.QueryRowContext(ctx, getSkillScriptAuditByFile, arg.ProjectID, arg.SkillFileID)
	var i SkillScriptAudit
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SkillID,
		&i.SkillFileID,
		&i.RelativePath,
		&i.Runtime,
		&i.DestructiveOperations,
		&i.FilesystemAccess,
		&i.NetworkAccess,
		&i.ExternalDependencies,
		&i.ExpectedInputsJson,
		&i.ExpectedOutputsJson,
		&i.RiskNotes,
		&i.Recommendation,
		&i.AuditedAt,
	)
	return i, err
}

const listEnabledSkillScriptApprovals = `-- name: ListEnabledSkillScriptApprovals :many
SELECT skill_script_approvals.id, skill_script_approvals.project_id, skill_script_approvals.skill_id, skill_script_approvals.skill_file_id, skill_script_approvals.audit_id, skill_script_approvals.enabled, skill_script_approvals.runtime_command, skill_script_approvals.timeout_ms, skill_script_approvals.max_stdout_bytes, skill_script_approvals.max_stderr_bytes, skill_script_approvals.allow_network, skill_script_approvals.allow_project_files, skill_script_approvals.approved_by, skill_script_approvals.approved_at, skill_script_approvals.updated_at
FROM skill_script_approvals
JOIN skills ON skills.id = skill_script_approvals.skill_id
WHERE skill_script_approvals.project_id = ?
  AND skill_script_approvals.enabled = 1
ORDER BY skills.name ASC, skill_script_approvals.skill_file_id ASC
`

func (q *Queries) ListEnabledSkillScriptApprovals(ctx context.Context, projectID string) ([]SkillScriptApproval, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledSkillScriptApprovals, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SkillScriptApproval
	for rows.Next() {
		var i SkillScriptApproval
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SkillID,
			&i.SkillFileID,
			&i.AuditID,
			&i.Enabled,
			&i.RuntimeCommand,
			&i.TimeoutMs,
			&i.MaxStdoutBytes,
			&i.MaxStderrBytes,
			&i.AllowNetwork,
			&i.AllowProjectFiles,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillScriptAudits = `-- name: ListSkillScriptAudits :many
SELECT id, project_id, skill_id, skill_file_id, relative_path, runtime, destructive_operations, filesystem_access, network_access, external_dependencies, expected_inputs_json, expected_outputs_json, risk_notes, recommendation, audited_at FROM skill_script_audits
WHERE project_id = ? AND skill_id = ?
ORDER BY relative_path ASC
`

type ListSkillScriptAuditsParams struct {
	ProjectID string `json:"project_id"`
	SkillID   string `json:"skill_id"`
}

func (q *Queries) ListSkillScriptAudits(ctx context.Context, arg ListSkillScriptAuditsParams) ([]SkillScriptAudit, error) {
	rows, err := q.db.QueryContext(ctx, listSkillScriptAudits, arg.ProjectID, arg.SkillID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SkillScriptAudit
	for rows.Next() {
		var i SkillScriptAudit
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SkillID,
			&i.SkillFileID,
			&i.RelativePath,
			&i.Runtime,
			&i.DestructiveOperations,
			&i.FilesystemAccess,
			&i.NetworkAccess,
			&i.ExternalDependencies,
			&i.ExpectedInputsJson,
			&i.ExpectedOutputsJson,
			&i.RiskNotes,
			&i.Recommendation,
			&i.AuditedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillScriptRunsByProject = `-- name: ListSkillScriptRunsByProject :many
SELECT id, project_id, session_id, skill_id, skill_file_id, approval_id, tool_call_id, status, output_kind, input_json, output_json, stdout_text, stderr_text, exit_code, duration_ms, error_message, created_at FROM skill_script_runs
WHERE project_id = ?
ORDER BY created_at DESC
LIMIT ?
`

type ListSkillScriptRunsByProjectParams struct {
	ProjectID string `json:"project_id"`
	Limit     int64  `json:"limit"`
}

func (q *Queries) ListSkillScriptRunsByProject(ctx context.Context, arg ListSkillScriptRunsByProjectParams) ([]SkillScriptRun, error) {
	rows, err := q.db.QueryContext(ctx, listSkillScriptRunsByProject, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SkillScriptRun
	for rows.Next() {
		var i SkillScriptRun
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SessionID,
			&i.SkillID,
			&i.SkillFileID,
			&i.ApprovalID,
			&i.ToolCallID,
			&i.Status,
			&i.OutputKind,
			&i.InputJson,
			&i.OutputJson,
			&i.StdoutText,
			&i.StderrText,
			&i.ExitCode,
			&i.DurationMs,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillScriptRunsBySession = `-- name: ListSkillScriptRunsBySession :many
SELECT id, project_id, session_id, skill_id, skill_file_id, approval_id, tool_call_id, status, output_kind, input_json, output_json, stdout_text, stderr_text, exit_code, duration_ms, error_message, created_at FROM skill_script_runs
WHERE project_id = ? AND session_id = ?
ORDER BY created_at DESC
LIMIT ?
`

type ListSkillScriptRunsBySessionParams struct {
	ProjectID string         `json:"project_id"`
	SessionID sql.NullString `json:"session_id"`
	Limit     int64          `json:"limit"`
}

func (q *Queries) ListSkillScriptRunsBySession(ctx context.Context, arg ListSkillScriptRunsBySessionParams) ([]SkillScriptRun, error) {
	rows, err := q.db.QueryContext(ctx, listSkillScriptRunsBySession, arg.ProjectID, arg.SessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SkillScriptRun
	for rows.Next() {
		var i SkillScriptRun
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SessionID,
			&i.SkillID,
			&i.SkillFileID,
			&i.ApprovalID,
			&i.ToolCallID,
			&i.Status,
			&i.OutputKind,
			&i.InputJson,
			&i.OutputJson,
			&i.StdoutText,
			&i.StderrText,
			&i.ExitCode,
			&i.DurationMs,
			&i.ErrorMessage,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSkillScriptApproval = `-- name: UpsertSkillScriptApproval :exec
INSERT INTO skill_script_approvals (
  id, project_id, skill_id, skill_file_id, audit_id, enabled, runtime_command,
  timeout_ms, max_stdout_bytes, max_stderr_bytes, allow_network,
  allow_project_files, approved_by, approved_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(project_id, skill_file_id) DO UPDATE SET
  audit_id = excluded.audit_id,
  enabled = excluded.enabled,
  runtime_command = excluded.runtime_command,
  timeout_ms = excluded.timeout_ms,
  max_stdout_bytes = excluded.max_stdout_bytes,
  max_stderr_bytes = excluded.max_stderr_bytes,
  allow_network = excluded.allow_network,
  allow_project_files = excluded.allow_project_files,
  approved_by = excluded.approved_by,
  updated_at = excluded.updated_at
`

type UpsertSkillScriptApprovalParams struct {
	ID                string `json:"id"`
	ProjectID         string `json:"project_id"`
	SkillID           string `json:"skill_id"`
	SkillFileID       string `json:"skill_file_id"`
	AuditID           string `json:"audit_id"`
	Enabled           int64  `json:"enabled"`
	RuntimeCommand    string `json:"runtime_command"`
	TimeoutMs         int64  `json:"timeout_ms"`
	MaxStdoutBytes    int64  `json:"max_stdout_bytes"`
	MaxStderrBytes    int64  `json:"max_stderr_bytes"`
	AllowNetwork      int64  `json:"allow_network"`
	AllowProjectFiles int64  `json:"allow_project_files"`
	ApprovedBy        string `json:"approved_by"`
	ApprovedAt        string `json:"approved_at"`
	UpdatedAt         string `json:"updated_at"`
}

func (q *Queries) UpsertSkillScriptApproval(ctx context.Context, arg UpsertSkillScriptApprovalParams) error {
	_, err := q.db.ExecContext(ctx, upsertSkillScriptApproval,
		arg.ID,
		arg.ProjectID,
		arg.SkillID,
		arg.SkillFileID,
		arg.AuditID,
		arg.Enabled,
		arg.RuntimeCommand,
		arg.TimeoutMs,
		arg.MaxStdoutBytes,
		arg.MaxStderrBytes,
		arg.AllowNetwork,
		arg.AllowProjectFiles,
		arg.ApprovedBy,
		arg.ApprovedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertSkillScriptAudit = `-- name: UpsertSkillScriptAudit :exec
INSERT INTO skill_script_audits (
  id, project_id, skill_id, skill_file_id, relative_path, runtime,
  destructive_operations, filesystem_access, network_access, external_dependencies,
  expected_inputs_json, expected_outputs_json, risk_notes, recommendation, audited_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(project_id, skill_file_id) DO UPDATE SET
  runtime = excluded.runtime,
  destructive_operations = excluded.destructive_operations,
  filesystem_access = excluded.filesystem_access,
  network_access = excluded.network_access,
  external_dependencies = excluded.external_dependencies,
  expected_inputs_json = excluded.expected_inputs_json,
  expected_outputs_json = excluded.expected_outputs_json,
  risk_notes = excluded.risk_notes,
  recommendation = excluded.recommendation,
  audited_at = excluded.audited_at
`

type UpsertSkillScriptAuditParams struct {
	ID                    string `json:"id"`
	ProjectID             string `json:"project_id"`
	SkillID               string `json:"skill_id"`
	SkillFileID           string `json:"skill_file_id"`
	RelativePath          string `json:"relative_path"`
	Runtime               string `json:"runtime"`
	DestructiveOperations int64  `json:"destructive_operations"`
	FilesystemAccess      string `json:"filesystem_access"`
	NetworkAccess         int64  `json:"network_access"`
	ExternalDependencies  string `json:"external_dependencies"`
	ExpectedInputsJson    string `json:"expected_inputs_json"`
	ExpectedOutputsJson   string `json:"expected_outputs_json"`
	RiskNotes             string `json:"risk_notes"`
	Recommendation        string `json:"recommendation"`
	AuditedAt             string `json:"audited_at"`
}

func (q *Queries) UpsertSkillScriptAudit(ctx context.Context, arg UpsertSkillScriptAuditParams) error {
	_, err := q.db.ExecContext(ctx, upsertSkillScriptAudit,
		arg.ID,
		arg.ProjectID,
		arg.SkillID,
		arg.SkillFileID,
		arg.RelativePath,
		arg.Runtime,
		arg.DestructiveOperations,
		arg.FilesystemAccess,
		arg.NetworkAccess,
		arg.ExternalDependencies,
		arg.ExpectedInputsJson,
		arg.ExpectedOutputsJson,
		arg.RiskNotes,
		arg.Recommendation,
		arg.AuditedAt,
	)
	return err
}
