import { useEffect, useRef, useState } from 'react';
import { History, X } from 'lucide-react';
import { IconButton } from '../../shared/ui/edda';
import { loadHistory, loadFile, loadVersion, type ProjectVersion, type VersionPage } from './fileApi';
import { inspectFile, type FileView } from './fileModel';
import { FilePreview } from './FilePreview';
export function FileHistory({ version, busy, run, onClose, onRestore }: { version: ProjectVersion; busy: boolean; run: (work: () => Promise<void>) => Promise<void>; onClose: () => void; onRestore: (past: ProjectVersion) => void }) {
  const alive = useRef(true);
  useEffect(() => { alive.current = true; return () => { alive.current = false; }; }, []);
  const [history, setHistory] = useState<VersionPage | null>(null), [past, setPast] = useState<ProjectVersion | null>(null), [preview, setPreview] = useState<FileView | null>(null), [error, setError] = useState('');
  useEffect(() => { let cancelled = false; void loadHistory(version.projectId).then(value => { if (!cancelled) setHistory(value); }).catch(cause => { if (!cancelled) setError(cause instanceof Error ? cause.message : 'Не удалось загрузить историю.'); }); return () => { cancelled = true; }; }, [version.id]);
  useEffect(() => () => { if (preview) URL.revokeObjectURL(preview.url); }, [preview?.url]);
  return <aside className="context-panel" aria-label="История проекта"><header><h2>История проекта</h2><IconButton icon={X} label="Закрыть историю" onClick={onClose} /></header><p className="fine-print">Каждое сохранение создаёт версию всего проекта. Посмотрите её содержимое перед восстановлением.</p>{error && <p role="alert" className="form-error">{error}</p>}{!history && !error && <p role="status">Загружаем историю…</p>}{history?.versions.map(item => <button key={item.id} className={`revision-row ${past?.id === item.id ? 'chosen' : ''}`} disabled={busy} onClick={() => void run(async () => { setPast(await loadVersion(version.projectId, item.id)); setPreview(null); })}><History size={16} /><span>{new Date(item.createdAt).toLocaleString('ru')}<small>{item.id === version.id ? 'Текущая версия' : item.id.slice(-8)}</small></span></button>)}{history?.next && <button className="subtle-action" disabled={busy} onClick={() => void run(async () => { const next = await loadHistory(version.projectId, history.next); setHistory({ versions: [...history.versions, ...next.versions], next: next.next }); })}>Более ранние версии</button>}{past && <><h3 className="list-heading">Файлы выбранной версии</h3><div className="history-file-list">{past.entries.map(entry => <button key={entry.id} disabled={busy || entry.kind === 'directory'} onClick={() => void run(async () => { const next = await inspectFile(entry, await loadFile(past, entry)); if (alive.current) setPreview(next); else URL.revokeObjectURL(next.url); })}>{entry.path}</button>)}</div>{preview && <FilePreview key={preview.url} view={preview} compact />}<button className="quiet-button" disabled={busy || past.id === version.id} onClick={() => onRestore(past)}>Восстановить эту версию…</button></>}</aside>;
}
