import { useState } from 'react';
import { ChevronDown, ChevronRight, File, FileText, Folder, Image, MoreHorizontal } from 'lucide-react';
import type { TreeEntry } from './fileApi';
import { basename, dirname } from './fileModel';
import { IconButton } from '../../shared/ui/edda';

export function FileTree({ root = '', entries, selected, busy, query, dirtyIds, onOpen, onManage, onDrop }: { root?: string; entries: TreeEntry[]; selected?: string; busy: boolean; query: string; dirtyIds: Set<string>; onOpen: (entry: TreeEntry) => void; onManage: (entry: TreeEntry) => void; onDrop: (event: React.DragEvent, parent: string) => void }) {
  const [collapsed, setCollapsed] = useState(new Set<string>()), [target, setTarget] = useState<string | null>(null);
  function dragOver(event: React.DragEvent, path: string) { if (busy || !event.dataTransfer.types.some(type => type === 'Files' || type === 'application/x-edda-entry')) return; event.preventDefault(); event.stopPropagation(); event.dataTransfer.dropEffect = event.dataTransfer.types.includes('Files') ? 'copy' : 'move'; setTarget(path); }
  function children(parent: string, depth = 0): React.ReactNode {
    return entries.filter(entry => dirname(entry.path) === parent).sort((a, b) => Number(b.kind === 'directory') - Number(a.kind === 'directory') || a.path.localeCompare(b.path)).filter(entry => !query || entry.kind === 'directory' || entry.path.toLocaleLowerCase().includes(query.toLocaleLowerCase())).map(entry => {
      const folder = entry.kind === 'directory', closed = collapsed.has(entry.id) && !query;
      const Icon = folder ? Folder : /\.(png|jpe?g|gif|webp|avif|svg)$/i.test(entry.path) ? Image : /\.(md|txt|json|csv|ya?ml)$/i.test(entry.path) ? FileText : File;
      return <div key={entry.id} className="tree-branch"><div className={`tree-row ${selected === entry.id ? 'selected' : ''} ${target === entry.path ? 'drop-target' : ''}`} style={{ paddingLeft: 10 + depth * 14 }} draggable={!busy} onDragStart={event => { event.dataTransfer.setData('application/x-edda-entry', entry.id); event.dataTransfer.effectAllowed = 'move'; }} onDragEnd={() => setTarget(null)} onDragLeave={event => { if (!event.currentTarget.contains(event.relatedTarget as Node)) setTarget(null); }} onDragOver={folder ? event => dragOver(event, entry.path) : undefined} onDrop={folder ? event => { setTarget(null); onDrop(event, entry.path); } : undefined}><button className="tree-label" title={entry.path} disabled={busy} aria-current={selected === entry.id ? 'page' : undefined} aria-expanded={folder ? !closed : undefined} onClick={() => { if (folder) setCollapsed(old => { const next = new Set(old); next.has(entry.id) ? next.delete(entry.id) : next.add(entry.id); return next; }); else onOpen(entry); }}>{folder ? closed ? <ChevronRight size={13} /> : <ChevronDown size={13} /> : <span className="tree-indent" />}<Icon size={16} /><span>{basename(entry.path)}</span>{dirtyIds.has(entry.id) && <span className="dirty-mark" aria-label="Есть черновик" />}</button><IconButton className="tree-move" icon={MoreHorizontal} label={`Действия: ${entry.path}`} disabled={busy} onClick={() => onManage(entry)} /></div>{folder && !closed && children(entry.path, depth + 1)}</div>;
    });
  }
  return <><nav className="file-tree" aria-label="Файлы и папки">{children(root)}{entries.length === 0 && <p className="tree-empty">Добавьте первый текст или перетащите файлы сюда.</p>}{query && !entries.some(entry => entry.path.toLowerCase().includes(query.toLowerCase())) && <p className="tree-empty">Файлы не найдены</p>}</nav><div className={`root-drop ${target === root ? 'drop-target' : ''}`} onDragOver={event => dragOver(event, root)} onDragLeave={() => setTarget(null)} onDrop={event => { setTarget(null); onDrop(event, root); }}><Folder size={15} /><span>Перетащите сюда → {root || 'в корень'}</span></div></>;
}
