import { createHash } from 'node:crypto';
import { expect, test } from '@playwright/test';
import { loginForTest } from './auth';
import type { ProjectVersion, TreeEntry } from '../../src/features/files/fileApi';

test('author manages chapter order and metadata without a required draft stage', async ({page,request,isMobile},info)=>{
 const {token}=await(await loginForTest(request)).json() as {token:string};
 const headers={Authorization:`Bearer ${token}`};
 await page.addInitScript(value=>localStorage.setItem('open_edda_token',value),token);
 const project=await(await request.post('/api/projects',{headers,data:{title:`Оглавление ${info.project.name}`,storageMode:'files'}})).json() as {id:string};
 const root=`/api/projects/${project.id}/files`;
 const head=async()=>await(await request.get(`${root}/versions/current`,{headers})).json() as ProjectVersion;
 const initial=await head();
 const manifest={schema_version:2,book_id:'1b4f1cad-c846-4551-a497-a745087f5de2',title:'Книга',future:{preserve:true},chapters:[{id:'0b4f1cad-c846-4551-a497-a745087f5de2',path:'one.md',title:'Первая',extra:42},{id:'2b4f1cad-c846-4551-a497-a745087f5de2',path:'missing.md',title:'Отсутствующая'}]};
 const entries:TreeEntry[]=[];
 for(const [id,path,body] of [['manifest','.pocket-editor.json',JSON.stringify(manifest)],['one','one.md','Текст 🐦\r\nбез черновика\n'],['two','two.md','Вторая глава'],['reviewed','reviewed.md','С рецензией'],['review','reviewed.review.json',JSON.stringify({chapter_id:'4b4f1cad-c846-4551-a497-a745087f5de2',source_path:'reviewed.md',chapter_note:'Заметка'})]]){
  const sha256=createHash('sha256').update(body).digest('hex');
  expect((await request.put(`${root}/objects/${sha256}`,{headers,data:body})).status()).toBe(204);
  entries.push({id,path,kind:'file',sha256,bytes:Buffer.byteLength(body)});
 }
 expect((await request.post(`${root}/versions`,{headers,data:{expectedVersion:initial.id,operationId:'import',entries}})).status()).toBe(201);
 await page.addInitScript(id=>localStorage.setItem(`edda.resume:${id}`,'one'),project.id);
 await page.goto(`/projects/${project.id}/files`);
 if(isMobile)await page.getByRole('button',{name:'Файлы проекта',exact:true}).click();
 await page.getByRole('button',{name:'Управление книгой',exact:true}).click();
 const dialog=page.getByRole('dialog');
 await dialog.getByRole('textbox',{name:'Название книги',exact:true}).fill('Моя книга');
 await dialog.getByRole('button',{name:'Поднять главу 2',exact:true}).click();
 await dialog.getByRole('textbox',{name:'Название главы 2',exact:true}).fill('Новое название');
 await dialog.getByRole('combobox',{name:'Добавить существующий текст',exact:true}).selectOption('two.md');
 await dialog.getByRole('combobox',{name:'Добавить существующий текст',exact:true}).selectOption('reviewed.md');
 await dialog.getByRole('textbox',{name:'Файл новой главы',exact:true}).fill('new.md');
 await dialog.getByRole('button',{name:'Создать главу',exact:true}).click();
 await dialog.getByRole('textbox',{name:'Название главы 5',exact:true}).fill('Новая глава');
 await page.screenshot({path:info.outputPath('book-management.png'),fullPage:true});
 await page.route(`**${root}/book`,async route=>{await route.fetch();await route.abort();},{times:1});
 await dialog.getByRole('button',{name:'Сохранить книгу',exact:true}).click();
 await expect(dialog.getByRole('alert')).toBeVisible();
 const lost=await head();
 await dialog.getByRole('button',{name:'Сохранить книгу',exact:true}).click();
 await expect(dialog).toHaveCount(0);expect((await head()).id).toBe(lost.id);
 const saved=await(await request.get(`${root}/versions/${lost.id}/entries/manifest`,{headers})).json();
 expect(saved.chapters.map((c:{path:string})=>c.path)).toEqual(['missing.md','one.md','two.md','reviewed.md','new.md']);
 expect(saved.chapters[3].id).toBe('4b4f1cad-c846-4551-a497-a745087f5de2');
 const created=lost.entries.find(e=>e.path==='new.md')!;
 expect(await(await request.get(`${root}/versions/${lost.id}/entries/${created.id}`,{headers})).text()).toBe('# Новая глава\n');
 expect(lost.entries.find(e=>e.id==='review')?.sha256).toBe(entries.find(e=>e.id==='review')?.sha256);
 expect(saved.future).toEqual({preserve:true});expect(saved.chapters[1].extra).toBe(42);
 await expect(page.getByRole('navigation',{name:'Главы книги'}).getByRole('button',{name:/Отсутствующая/})).toBeDisabled();
 await page.getByRole('navigation',{name:'Главы книги'}).getByRole('button',{name:/Новое название/}).click();
 await page.getByRole('button',{name:'Метаданные главы',exact:true}).click();
 await dialog.getByRole('textbox',{name:'Свойства YAML',exact:true}).fill('title: Авторское название\nstatus: В работе\ncustom: [a, b]');
 await dialog.getByRole('button',{name:'Сохранить метаданные',exact:true}).click();
 await expect(dialog).toHaveCount(0);
 const updated=await head();
 const body=await(await request.get(`${root}/versions/${updated.id}/entries/one`,{headers})).body();
 expect(body.toString()).toBe('---\r\ntitle: Авторское название\r\nstatus: В работе\r\ncustom: [a, b]\r\n---\r\nТекст 🐦\r\nбез черновика\n');
 expect(updated.entries.map(e=>e.path)).toEqual(lost.entries.map(e=>e.path));
 expect(updated.entries.find(e=>e.id==='two')?.sha256).toBe(entries.find(e=>e.id==='two')?.sha256);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
});
