import { loginForTest } from './auth';
import { createHash } from 'node:crypto';
import { expect, test } from '@playwright/test';
import type { ProjectVersion } from '../../src/features/files/fileApi';

test.beforeEach(async ({page}) => { await page.addInitScript(() => localStorage.setItem('edda.editor-mode', 'source')); });

test('real workspace retains drafts, resolves conflicts and retries lost save receipts', async ({ page, request, isMobile }, info) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  const response = await loginForTest(request);
  const { token } = await response.json() as { token: string }; const headers = { Authorization: `Bearer ${token}` };
  await page.addInitScript(value => localStorage.setItem('open_edda_token', value), token);
  await page.goto('/projects');
  await page.getByRole('button', { name: 'Создать проект', exact: true }).first().click();
  await page.getByLabel('Название проекта', { exact: true }).fill(`Тетрадь ${info.project.name} ${Date.now()}`);
  await page.getByRole('combobox', {name:/^Язык текста/}).selectOption('');
  const created = page.waitForResponse(response => response.url().endsWith('/api/projects') && response.request().method() === 'POST');
  await page.getByRole('button', { name: 'Создать проект', exact: true }).click();
  expect((await (await created).json()).language).toBe('');
  await expect(page).toHaveURL(/\/files$/);
  const root = `/api/projects/${page.url().split('/').at(-2)}/files`;
  const files = async () => { if(isMobile && !await page.getByRole('button',{name:'Создать файл',exact:true}).isVisible()) await page.getByRole('button',{name:'Файлы проекта',exact:true}).click(); };
  await files(); await page.getByRole('button',{name:'Создать папку',exact:true}).click();
  await page.getByLabel('Имя',{exact:true}).fill('kb'); await page.getByRole('button',{name:'Создать',exact:true}).click();
  await expect(page.getByRole('button',{name:'kb',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Создать файл',exact:true}).click();
  await page.getByLabel('Имя',{exact:true}).fill('заметки.md'); await page.getByRole('combobox',{name:'Папка',exact:true}).selectOption('kb');
  await page.getByRole('button',{name:'Создать',exact:true}).click();
  const text = page.getByLabel('Текст файла',{exact:true}); await expect(text).toHaveValue('');
  const originalText = '# Начало\n\nНа полях остались заметки.\n'; await text.fill(originalText);
  await page.getByRole('button',{name:'Сохранить файл',exact:true}).click(); await expect(page.locator('.save-label')).toHaveText('Сохранено'); await expect(page.getByRole('button',{name:'Сохранить файл',exact:true})).toBeDisabled();
  const original = await (await request.get(`${root}/versions/current`,{headers})).json() as ProjectVersion;
  const file = original.entries.find(e => e.kind === 'file')!;
  await text.fill('Мой несохранённый текст.'); page.once('dialog',dialog => dialog.accept()); await page.reload();
  await expect(text).toHaveValue('Мой несохранённый текст.');
  // Navigating to a second text and back does not discard either draft.
  await files(); await page.getByRole('button',{name:'Создать файл',exact:true}).click();
  await page.getByLabel('Имя',{exact:true}).fill('второй.md'); await page.getByRole('button',{name:'Создать',exact:true}).click();
  await expect(text).toHaveValue(''); await text.fill('Второй черновик');
  await files(); await page.getByRole('button',{name:/^заметки\.md/}).click(); await expect(text).toHaveValue('Мой несохранённый текст.');
  const head = await (await request.get(`${root}/versions/current`,{headers})).json() as ProjectVersion;
  const remote = 'Изменение с другого компьютера.\n', hash = createHash('sha256').update(remote).digest('hex');
  expect((await request.put(`${root}/objects/${hash}`,{headers:{...headers,'Content-Type':'application/octet-stream'},data:remote})).status()).toBe(204);
  expect((await request.post(`${root}/versions`,{headers,data:{expectedVersion:head.id,operationId:`remote-${info.project.name}`,entries:head.entries.map(e => e.id===file.id ? {...e,sha256:hash,bytes:Buffer.byteLength(remote)} : e)}})).status()).toBe(201);
  await page.getByRole('button',{name:'Сохранить файл',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Две версии одного текста'})).toBeVisible();
  await expect(page.getByText(remote.trim(),{exact:true})).toBeVisible();
  await page.screenshot({path:info.outputPath('conflict.png'),fullPage:true});
  await page.getByRole('button',{name:'Отказаться от моего черновика',exact:true}).click(); await expect(text).toHaveValue(remote);
  await text.fill('Последняя редакция.\n');
  await page.route(`**${root}/versions`,async route => {await route.fetch();await route.abort();},{times:1});
  await page.getByRole('button',{name:'Сохранить файл',exact:true}).click(); await expect(page.getByRole('alert')).toBeVisible();
  const lost = await (await request.get(`${root}/versions/current`,{headers})).json() as ProjectVersion;
  await page.getByRole('button',{name:'Сохранить файл',exact:true}).click(); await expect(page.locator('.save-label')).toHaveText('Сохранено'); await expect(page.getByRole('button',{name:'Сохранить файл',exact:true})).toBeDisabled();
  const retried = await (await request.get(`${root}/versions/current`,{headers})).json() as ProjectVersion; expect(retried.id).toBe(lost.id);
  expect(await (await request.get(`${root}/versions/${original.id}/entries/${file.id}`,{headers})).text()).toBe(originalText);
  await files(); await page.getByRole('button',{name:/^второй\.md/}).click(); await expect(text).toHaveValue('Второй черновик');
  await page.screenshot({path:info.outputPath('workspace.png'),fullPage:true});
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy(); expect(errors).toEqual([]);
});

test('imports previewable and binary files, preserves move identity and restores history',async ({page,request,isMobile},info) => {
  const response=await loginForTest(request);
  const {token}=await response.json() as {token:string}; const headers={Authorization:`Bearer ${token}`};
  await page.addInitScript(value=>localStorage.setItem('open_edda_token',value),token);
  const projectTitle = `Files ${info.project.name} ${Date.now()}`;
  const project=await (await request.post('/api/projects',{headers,data:{title:projectTitle,storageMode:'files'}})).json() as {id:string};
  const root=`/api/projects/${project.id}/files`;
  await page.goto(`/projects/${project.id}/files`);
  const files=async()=>{if(isMobile&&!await page.getByRole('button',{name:'Создать файл',exact:true}).isVisible())await page.getByRole('button',{name:'Файлы проекта',exact:true}).click();};
  await expect(page.getByRole('heading',{name:projectTitle,exact:true})).toBeVisible();
  await page.locator('input[type=file]').first().setInputFiles([{name:'章.md',mimeType:'text/markdown',buffer:Buffer.from('# 原稿\n')},{name:'cover.bin',mimeType:'application/octet-stream',buffer:Buffer.from([0,255,13,10])},{name:'cover.svg',mimeType:'image/svg+xml',buffer:Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="200" height="150"><rect width="200" height="150" fill="#376452"/></svg>')}]);
  await page.getByRole('button',{name:'Добавить файлы',exact:true}).last().click(); await expect(page.getByLabel('Текст файла',{exact:true})).toHaveValue('# 原稿\n');
  const original=await (await request.get(`${root}/versions/current`,{headers})).json() as ProjectVersion;
  await files(); await page.getByRole('button',{name:'cover.bin',exact:true}).click(); await expect(page.getByRole('heading',{name:'Файл готов к скачиванию',exact:true})).toBeVisible(); expect(await page.getByRole('alert').count()).toBe(0);
  const downloaded=page.waitForEvent('download');await page.getByRole('button',{name:'Скачать файл',exact:true}).last().click();expect((await downloaded).suggestedFilename()).toBe('cover.bin');
  await files();await page.getByRole('button',{name:'cover.svg',exact:true}).click();await expect(page.getByRole('img',{name:'cover.svg',exact:true})).toBeVisible();
  await files();await page.getByRole('button',{name:'Действия: 章.md',exact:true}).click();await page.getByLabel('Имя',{exact:true}).fill('renamed.md');await page.getByRole('button',{name:'Сохранить изменения',exact:true}).click();
  // The click starts an asynchronous rename; wait for its successful UI completion.
  await expect(page.getByRole('button',{name:'Сохранить изменения',exact:true})).toHaveCount(0);
  const renamed=await (await request.get(`${root}/versions/current`,{headers})).json() as ProjectVersion;expect(renamed.entries.find(e=>e.path==='renamed.md')?.id).toBe(original.entries.find(e=>e.path==='章.md')?.id);
  await page.getByRole('button',{name:'Создать папку',exact:true}).click();await page.getByLabel('Имя',{exact:true}).fill('materials');await page.getByRole('button',{name:'Создать',exact:true}).click();
  if(!isMobile){await page.getByRole('button',{name:'renamed.md',exact:true}).dragTo(page.getByRole('button',{name:'materials',exact:true}));await expect.poll(async()=> (await (await request.get(`${root}/versions/current`,{headers})).json() as ProjectVersion).entries.find(e=>e.id===original.entries.find(e=>e.path==='章.md')?.id)?.path).toBe('materials/renamed.md');}
  await page.getByRole('button',{name:'Действия: cover.bin',exact:true}).click();await page.getByRole('button',{name:'Удалить…',exact:true}).click();await page.getByRole('button',{name:'Удалить из проекта',exact:true}).click();await expect(page.getByRole('button',{name:'cover.bin',exact:true})).toHaveCount(0);
  if(isMobile)await page.getByRole('button',{name:'Закрыть файлы',exact:true}).click();
  await page.getByRole('button',{name:'История проекта',exact:true}).click();
  await page.locator('.revision-row').filter({hasText:original.id.slice(-8)}).click();
  await page.locator('.history-file-list').getByRole('button',{name:'章.md',exact:true}).click();await expect(page.locator('.history-preview pre')).toContainText('# 原稿');
  await page.getByRole('button',{name:'Восстановить эту версию…',exact:true}).click();await page.getByRole('button',{name:'Восстановить весь проект',exact:true}).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);const restored=await (await request.get(`${root}/versions/current`,{headers})).json() as ProjectVersion;expect(restored.entries).toEqual(original.entries);expect(restored.id).not.toBe(original.id);
  await files(); await page.getByRole('button',{name:'Настройки вида',exact:true}).click();await page.getByRole('button',{name:'Тёмное',exact:true}).click();await page.getByRole('button',{name:'Закрыть',exact:true}).click();
  await expect(page.locator('html')).toHaveAttribute('data-theme','dark');await page.screenshot({path:info.outputPath('dark-files.png'),fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBeTruthy();
});
