import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { expect, test } from '@playwright/test';
import { loginForTest } from './auth';
import type { ProjectVersion, TreeEntry } from '../../src/features/files/fileApi';

test.use({ actionTimeout: 10_000 });
const body = readFileSync(new URL('../../../project/testdata/pocket/chapter.md', import.meta.url));
const review = readFileSync(new URL('../../../project/testdata/pocket/chapter.review.json', import.meta.url));
const manifest = readFileSync(new URL('../../../project/testdata/pocket/manifest.json', import.meta.url));

test('author keeps reviews while editing, saves drafts, applies atomically and retries a lost response', async ({ page, request }, info) => {
  const { token } = await (await loginForTest(request)).json() as { token: string };
  const headers = { Authorization: `Bearer ${token}` };
  await page.addInitScript(value => localStorage.setItem('open_edda_token', value), token);
  const project = await (await request.post('/api/projects', { headers, data: { title: `Review ${info.project.name}`, storageMode: 'files' } })).json() as { id: string };
  const root = `/api/projects/${project.id}/files`;
  const head = async () => await (await request.get(`${root}/versions/current`, { headers })).json() as ProjectVersion;
  const initial = await head();
  const entries: TreeEntry[] = [];
  for (const [id, path, data] of [['chapter','chapter.md',body], ['manifest','.pocket-editor.json',manifest], ['review','chapter.review.json',review]] as const) {
    const sha256 = createHash('sha256').update(data).digest('hex');
    expect((await request.put(`${root}/objects/${sha256}`, { headers, data })).status()).toBe(204);
    entries.push({ id, path, kind: 'file', sha256, bytes: data.length });
  }
  expect((await request.post(`${root}/versions`, { headers, data: { expectedVersion: initial.id, operationId: 'import', entries } })).status()).toBe(201);
  await page.addInitScript(id => localStorage.setItem(`edda.resume:${id}`, 'chapter'), project.id);
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error' && message.text().includes('flushSync')) errors.push(message.text()); });
  await page.goto(`/projects/${project.id}/files`);
  const panel = page.getByRole('complementary', { name: 'Рецензия главы' });
  await panel.getByText('Заметка о главе', { exact: true }).click();
  await expect(panel.getByText('Проверить ритм вступления.', { exact: true })).toBeVisible();
  await panel.getByText('Заметка о главе', { exact: true }).click();
  const first = panel.locator('[data-record-id="a65eef9e-7318-4777-b2a2-c58a169bfcf6"]');
  await first.getByRole('button', { name: 'Показать в тексте:' }).click();
  await expect(page.locator('.pocket-mark-active').first()).toBeVisible();
  await page.getByRole('button', { name: 'Рецензирование', exact: true }).click();
  await expect(page.locator('.file-galley .cm-content')).toHaveAttribute('contenteditable', 'false');
  await expect(first.getByRole('button', { name: 'Принять правку' })).toBeEnabled();
  await page.getByRole('button', { name: 'Редактирование', exact: true }).click();
  const editor = page.locator('.file-galley .cm-content');
  await editor.click();
  await page.keyboard.press('Control+End');
  await page.keyboard.type('Авторская строка.');
  await expect(first.getByRole('button', { name: 'Принять правку' })).toBeDisabled();
  await page.getByRole('button', { name: 'Рецензирование', exact: true }).click();
  await expect(editor).toContainText('Авторская строка.');
  await page.getByRole('button', { name: 'Редактирование', exact: true }).click();
  await panel.getByRole('button', { name: 'Сохранить и проверить привязки' }).click();
  await expect(first.getByRole('button', { name: 'Принять правку' })).toBeEnabled();
  await page.route(`**${root}/review`, async route => { await route.fetch(); await route.abort(); }, { times: 1 });
  await first.getByRole('button', { name: 'Принять правку' }).click();
  await expect(page.getByRole('alert')).toBeVisible();
  const applied = await head();
  await first.getByRole('button', { name: 'Принять правку' }).click();
  await expect(first).toHaveCount(0);
  expect((await head()).id).toBe(applied.id);
  await expect(editor).toContainText('Он совсем тихо сказал: привет.');
  await expect(editor).toContainText('Авторская строка.');
  await expect(page.getByRole('button', { name: 'Редактирование', exact: true })).toHaveAttribute('aria-pressed', 'true');
  const persisted = await (await request.get(`${root}/versions/${applied.id}/entries/chapter`, { headers })).text();
  expect(persisted).toContain('Авторская строка.');
  writeFileSync(info.outputPath('accepted-chapter.md'), persisted);
  await info.attach('accepted-chapter', { path: info.outputPath('accepted-chapter.md'), contentType: 'text/markdown' });
  const annotations = await (await request.get(`${root}/versions/${applied.id}/entries/review`, { headers })).json() as { edits: unknown[]; signals: unknown[] };
  writeFileSync(info.outputPath('accepted-review.json'), JSON.stringify(annotations));
  await info.attach('accepted-review', { path: info.outputPath('accepted-review.json'), contentType: 'application/json' });
  expect(annotations.edits).toHaveLength(1); expect(annotations.signals).toHaveLength(2);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  expect(persisted).toContain('\r\n');
  expect(errors).toEqual([]);
  await page.screenshot({ path: info.outputPath('author-review.png'), fullPage: true });
  // A second client changes the chapter: a decision on the old version must fail.
  const remoteText = persisted + '\r\nПравка с другого устройства.\r\n';
  const remoteHash = createHash('sha256').update(remoteText).digest('hex');
  expect((await request.put(`${root}/objects/${remoteHash}`, { headers, data: remoteText })).status()).toBe(204);
  const remoteResponse = await request.post(`${root}/versions`, { headers, data: { expectedVersion: applied.id, operationId: 'remote-edit', entries: applied.entries.map(e => e.id === 'chapter' ? { ...e, sha256: remoteHash, bytes: Buffer.byteLength(remoteText) } : e) } });
  expect(remoteResponse.status()).toBe(201);
  const remoteVersion = await remoteResponse.json() as ProjectVersion;
  await panel.getByRole('button', { name: 'Принять правку' }).click();
  await expect(page.getByRole('alert')).toContainText('Проект изменился на другом устройстве');
  expect((await head()).id).toBe(remoteVersion.id);
  await page.getByRole('button', { name: 'Обновить файлы', exact: true }).click();
  await expect(editor).toContainText('Правка с другого устройства.');
  await expect(panel.getByRole('button', { name: 'Принять правку' })).toBeEnabled();
  // The author rewrites the remaining quoted word. Its stale proposal stays visible.
  await editor.fill('Автор переписал главу.');
  await panel.getByRole('button', { name: 'Сохранить и проверить привязки' }).click();
  const remaining = panel.locator('[data-record-id="b65eef9e-7318-4777-b2a2-c58a169bfcf6"]');
  await expect(remaining).toContainText('Привязка устарела');
  await expect(remaining.getByRole('button', { name: 'Принять правку' })).toBeDisabled();
  await remaining.getByRole('button', { name: 'Отклонить', exact: true }).click();
  await expect(remaining).toHaveCount(0);
  await expect(editor).toContainText('Автор переписал главу.');
  expect(errors).toEqual([]);
});

test('compose a first review without changing source and undo/redo individual decisions', async ({ page, request }, info) => {
  const { token } = await (await loginForTest(request)).json() as { token: string };
  const headers = { Authorization: `Bearer ${token}` };
  await page.addInitScript(value => localStorage.setItem('open_edda_token', value), token);
  const project = await (await request.post('/api/projects', { headers, data: { title: `Compose ${info.project.name}`, storageMode: 'files' } })).json() as { id: string };
  const root = `/api/projects/${project.id}/files`;
  const head = async () => await (await request.get(`${root}/versions/current`, { headers })).json() as ProjectVersion;
  const initial = await head(); const entries: TreeEntry[] = [];
  for (const [id, path, data] of [['chapter','chapter.md',body]] as const) {
    const sha256 = createHash('sha256').update(data).digest('hex');
    expect((await request.put(`${root}/objects/${sha256}`, { headers, data })).status()).toBe(204);
    entries.push({ id, path, kind: 'file', sha256, bytes: data.length });
  }
  expect((await request.post(`${root}/versions`, { headers, data: { expectedVersion: initial.id, operationId: 'import', entries } })).status()).toBe(201);
  await page.addInitScript(id => localStorage.setItem(`edda.resume:${id}`, 'chapter'), project.id);
  await page.goto(`/projects/${project.id}/files`);
  const panel = page.getByRole('complementary', { name: 'Рецензия главы' });
  await page.getByRole('button', { name: 'Рецензирование', exact: true }).click();
  await panel.getByRole('button', { name: 'Начать рецензию главы' }).click();
  await expect(panel).toContainText('Все замечания разобраны.');
  await page.getByRole('button', { name: 'Исходный Markdown', exact: true }).click();
  const source = page.getByRole('textbox', { name: 'Текст файла', exact: true });
  await source.evaluate((node: HTMLTextAreaElement) => { node.focus(); const i = node.value.indexOf('тихо'); node.setSelectionRange(i, i + 4); });
  await panel.getByRole('button', { name: 'Добавить к выделению' }).click();
  const dialog = page.getByRole('dialog');
  await expect(dialog.locator('blockquote')).toHaveText('тихо');
  await dialog.getByLabel('Тип рецензии', { exact: true }).selectOption('edit');
  await dialog.getByRole('textbox', { name: 'Предлагаемый текст', exact: true }).fill('негромко');
  await page.route(`**${root}/review`, async route => { await route.fetch(); await route.abort(); }, { times: 1 });
  await dialog.getByRole('button', { name: 'Сохранить рецензию' }).click();
  await expect(dialog.getByRole('alert')).toBeVisible();
  const lost = await head();
  await dialog.getByRole('button', { name: 'Сохранить рецензию' }).click();
  await expect(dialog).toHaveCount(0); expect((await head()).id).toBe(lost.id);
  await expect(panel).toContainText('негромко');
  expect(await (await request.get(`${root}/versions/${lost.id}/entries/chapter`, { headers })).body()).toEqual(body);
  await panel.getByRole('button', { name: 'Изменить рецензию', exact: true }).click();
  await expect(dialog.getByRole('button', { name: 'Сохранить рецензию' })).toBeDisabled();
  await dialog.getByRole('textbox', { name: 'Предлагаемый текст', exact: true }).fill('совсем тихо');
  await dialog.getByRole('button', { name: 'Сохранить рецензию' }).click();
  await expect(panel.locator('ins')).toHaveText('совсем тихо');
  await panel.getByRole('button', { name: 'Отменить решение' }).click();
  await expect(panel.locator('ins')).toHaveText('негромко');
  await panel.getByRole('button', { name: 'Повторить решение' }).click();
  await expect(panel.locator('ins')).toHaveText('совсем тихо');
  await panel.getByRole('button', { name: 'Принять правку' }).click();
  await expect(source).toHaveValue(/совсем тихо/);
  await panel.getByRole('button', { name: 'Отменить решение' }).click();
  await expect(source).not.toHaveValue(/совсем тихо/);
  await expect(panel.locator('ins')).toHaveText('совсем тихо');
  await page.getByRole('button', { name: 'Живой Markdown', exact: true }).click();
  await panel.getByRole('button', { name: 'Показать в тексте: тихо', exact: true }).click();
  await panel.getByRole('button', { name: 'Добавить к выделению' }).click();
  await dialog.getByRole('textbox', { name: 'Комментарий', exact: true }).fill('Уточнить интонацию.');
  await dialog.getByRole('button', { name: 'Сохранить рецензию' }).click();
  const signal = panel.locator('li').filter({ hasText: 'Уточнить интонацию.' });
  await signal.getByRole('button', { name: 'Изменить рецензию', exact: true }).click();
  await dialog.getByRole('textbox', { name: 'Комментарий', exact: true }).fill('Комментарий автора обновлён.');
  await dialog.getByRole('button', { name: 'Сохранить рецензию' }).click();
  await expect(panel).toContainText('Комментарий автора обновлён.');
  await panel.getByRole('button', { name: 'Изменить заметку о главе' }).click();
  await dialog.getByRole('textbox', { name: 'Заметка о главе', exact: true }).fill('Автор сам решает, когда текст готов.');
  await dialog.getByRole('button', { name: 'Сохранить рецензию' }).click();
  await panel.locator('summary').click();
  await expect(panel).toContainText('Автор сам решает, когда текст готов.');
  const final = await head(); const sidecar = final.entries.find(e => e.path === 'chapter.review.json')!;
  writeFileSync(info.outputPath('composed-chapter.md'), await (await request.get(`${root}/versions/${final.id}/entries/chapter`, { headers })).body());
  writeFileSync(info.outputPath('composed-review.json'), await (await request.get(`${root}/versions/${final.id}/entries/${sidecar.id}`, { headers })).body());
  const book = final.entries.find(e => e.path === '.pocket-editor.json')!;
  writeFileSync(info.outputPath('composed-manifest.json'), await (await request.get(`${root}/versions/${final.id}/entries/${book.id}`, { headers })).body());
});

test('confirmed review decisions survive failed refreshes without duplicate undo entries', async ({ page, request }, info) => {
  const { token } = await (await loginForTest(request)).json() as { token: string };
  const headers = { Authorization: `Bearer ${token}` };
  await page.addInitScript(value => localStorage.setItem('open_edda_token', value), token);
  const project = await (await request.post('/api/projects', { headers, data: { title: `Refresh failure ${info.project.name}`, storageMode: 'files' } })).json() as { id: string };
  const root = `/api/projects/${project.id}/files`;
  const head = async () => await (await request.get(`${root}/versions/current`, { headers })).json() as ProjectVersion;
  const initial = await head(); const entries: TreeEntry[] = [];
  for (const [id, path, data] of [['chapter', 'chapter.md', body], ['manifest', '.pocket-editor.json', manifest]] as const) {
    const sha256 = createHash('sha256').update(data).digest('hex');
    expect((await request.put(`${root}/objects/${sha256}`, { headers, data })).status()).toBe(204);
    entries.push({ id, path, kind: 'file', sha256, bytes: data.length });
  }
  expect((await request.post(`${root}/versions`, { headers, data: { expectedVersion: initial.id, operationId: 'import', entries } })).status()).toBe(201);
  await page.addInitScript(id => localStorage.setItem(`edda.resume:${id}`, 'chapter'), project.id);
  await page.goto(`/projects/${project.id}/files`);
  const panel = page.getByRole('complementary', { name: 'Рецензия главы' });
  const dialog = page.getByRole('dialog');
  const undo = panel.getByRole('button', { name: 'Отменить решение', exact: true });
  const redo = panel.getByRole('button', { name: 'Повторить решение', exact: true });
  const failRefresh = () => page.route(`**${root}/versions/current`, route => route.abort(), { times: 1 });
  const refresh = () => page.getByRole('button', { name: 'Обновить файлы', exact: true }).click();
  await panel.getByRole('button', { name: 'Изменить заметку о главе' }).click();
  await dialog.getByRole('textbox', { name: 'Заметка о главе', exact: true }).fill('Сохранённое решение');
  await failRefresh();
  await dialog.getByRole('button', { name: 'Сохранить рецензию' }).click();
  await expect(dialog.getByRole('alert')).toBeVisible();
  await dialog.getByRole('button', { name: 'Закрыть', exact: true }).click();
  await refresh();
  await expect(panel.locator('.review-note')).toContainText('Сохранённое решение');
  await expect(undo).toBeEnabled();
  await failRefresh(); await undo.click();
  await expect(page.getByRole('alert')).toBeVisible(); await refresh();
  await expect(panel.locator('.review-note')).toHaveCount(0);
  await expect(undo).toBeDisabled(); await expect(redo).toBeEnabled();
  await failRefresh(); await redo.click();
  await expect(page.getByRole('alert')).toBeVisible(); await refresh();
  await expect(panel.locator('.review-note')).toContainText('Сохранённое решение');
  await undo.click(); await expect(undo).toBeDisabled();
  // Retry the same confirmed mutation after refresh fails: one server version,
  // one history entry, even though the success response is received twice.
  await panel.getByRole('button', { name: 'Изменить заметку о главе' }).click();
  await dialog.getByRole('textbox', { name: 'Заметка о главе', exact: true }).fill('Повтор после сбоя');
  await failRefresh(); await dialog.getByRole('button', { name: 'Сохранить рецензию' }).click();
  await expect(dialog.getByRole('alert')).toBeVisible(); const saved = await head();
  await dialog.getByRole('button', { name: 'Сохранить рецензию' }).click();
  await expect(dialog).toHaveCount(0); expect((await head()).id).toBe(saved.id);
  await undo.click(); await expect(undo).toBeDisabled();
  await expect(panel.locator('.review-note')).toHaveCount(0);
});
